### ISSUE TITLE
Have plan to provide VueJS SSR template?

### ISSUE THREAD

**Issue by liamwang** [aspnet/JavaScriptServices#1042] opened 2017-06-17 14:14 UTC
Really need VueJS SSR template with .NET integrated. If someone has achieved one recently or in the future, please share a repo link and  '@' me to let me know. I will appreciate it very much.

**Comment by MarkPieszak** [comment] 2017-06-17 17:55
Duplicate of #1036 you can read the comments there for an implementation of SSR within Vue

**Comment by liamwang** [comment] 2017-06-18 02:29
@MarkPieszak Thank you for replying. I hav tried that implementation, but it doesn't work when published (I'v already opened an issue there), and it has not been maintained for a long time. 

I'm not good at node.js, so I opened this issue to get some help, asking for a good implementation.

**Comment by SteveSandersonMS** [comment] 2017-06-19 12:46
Thanks for the answer @markpieszak. Closing as duplicate.

**Closed by SteveSandersonMS** 2017-06-19 12:46 UTC
