### ISSUE TITLE
NodeInvocationException: Prerendering failed because of error: TypeError: Cannot read property 'forRoot' of undefined

### ISSUE THREAD

**Issue by RCneupane** [aspnet/JavaScriptServices#1624] opened 2018-04-23 10:33 UTC
#I'm using dot net core 2.0 with angular 5. when i,m trying to build in development mode im getting this issue.  Its showing  

> NodeInvocationException: Prerendering failed because of error: TypeError: Cannot read property 'forRoot' of undefined

But I've already defined forRoot

## An unhandled exception occurred while processing the request.

`NodeInvocationException: Prerendering failed because of error: TypeError: Cannot read property 'forRoot' of undefined
at eval (webpack-internal:///561:23:19) at eval (webpack-internal:///561:23:19)
at Object.<anonymous> (C:\Users\RAM CHANDRA\Source\Workspaces\Workspace\Project Troper\Troper.Web\ClientApp\dist\main-server.js:3812:1)
at __webpack_require__ (C:\Users\RAM CHANDRA\Source\Workspaces\Workspace\Project Troper\Troper.Web\ClientApp\dist\main-server.js:20:30)
at eval (webpack-internal:///1149:8:92)
at Object.<anonymous> (C:\Users\RAM CHANDRA\Source\Workspaces\Workspace\Project Troper\Troper.Web\ClientApp\dist\main-server.js:7961:1)
at __webpack_require__ (C:\Users\RAM CHANDRA\Source\Workspaces\Workspace\Project Troper\Troper.Web\ClientApp\dist\main-server.js:20:30)
at eval (webpack-internal:///740:16:77)
at Object.<anonymous> (C:\Users\RAM CHANDRA\Source\Workspaces\Workspace\Project Troper\Troper.Web\ClientApp\dist\main-server.js:4918:1)
at __webpack_require__ (C:\Users\RAM CHANDRA\Source\Workspaces\Workspace\Project Troper\Troper.Web\ClientApp\dist\main-server.js:20:30)
at eval (webpack-internal:///724:5:70)
Current directory is: C:\Users\RAM CHANDRA\Source\Workspaces\Workspace\Project Troper\Troper.Web`

> Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()

`Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance+<InvokeExportAsync>d__13.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.NodeServices.NodeServicesImpl+<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.NodeServices.NodeServicesImpl+<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Asp2017.Server.Helpers.HttpRequestExtensions+<BuildPrerender>d__1.MoveNext() in HttpRequestExtensions.cs
+
      return await Prerenderer.RenderToString(
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
AspCoreServer.Controllers.HomeController+<Index>d__0.MoveNext() in HomeController.cs
+
      var prerenderResult = await Request.BuildPrerender();
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware+<Invoke>d__3.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()`

**Comment by SteveSandersonMS** [comment] 2018-05-29 10:31
If you have some minimal repro steps for this, I'd be happy to take a look in case I can identify the cause. 

However this is an Angular question (as in, it's a Webpack build error with an Angular project, so ASP.NET Core isn't really involved during that phase). So you might get a quicker resolution by posting to the Angular community.

Closing due to lack of info but please feel free to post more info such as a minimal repro below. Hope that's OK!

**Closed by SteveSandersonMS** 2018-05-29 10:31 UTC
