### ISSUE TITLE
Angular CLI hot reload slow under IIS Express

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aspnet/JavaScriptServices#1445] opened 2017-12-18 05:29 UTC
I've got a default app generated with `dotnet new angular` and `Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0-preview1-final`.

When I run the project and then change any files according to the output log recompilation happens immediately. But the browser waits for 5-10 seconds before reloading a page. This only happens under IIS Express debugging, `dotnet run` is not affected.

Looking at the websocket activity in the browser, `a["{\"type\":\"ok\"}"]` message comes in without delays.

**Comment by SteveSandersonMS** [comment] 2018-01-02 10:05
That's interesting, however it's outside the control of anything in this repo, because everything here is agnostic to the host server (the code here doesn't know whether it's in IIS Express or directly under Kestrel).

@BillHiebert Do you know where IIS Express-specific perf issues should be reported? Is it to https://github.com/aspnet/Tooling/issues?

**Comment by BillHiebert** [comment] 2018-01-02 15:58
@SteveSandersonMS This could be a number of things and an ETL trace would be the best way to see what is happening. 

@MaximBalaganskiy Which files do you modify?  I want to see if I can reproduce this.

**Comment by MaximBalaganskiy** [comment] 2018-01-02 22:36
Any html or TS file changes trigger recompilation according to server trace
logs. I used the default template without any modifications.

**Comment by Alex-Torres** [comment] 2018-01-03 22:19
Having same problem.

**Comment by BillHiebert** [comment] 2018-01-04 21:51
I've opened an internal issue to gather performance traces to understand and address this.

**Comment by Alex-Torres** [comment] 2018-01-05 06:20
Thank you @BillHiebert , really appreciate all the work behind these new changes, I think this up and coming  enhancements will help a ton of people who use the Angular CLI, but want to use it with Asp.net Core.  Also, some enterprises still use Windows Authentication, and using IIS is just ideal.

**Comment by BillHiebert** [comment] 2018-01-05 16:49
@Alex-Torres A couple more questions:

- Which browser are you using and if using Chrome or IE, is script debugging enabled? If you do have script debugging enabled, can you disable it by unchecking the "Enable JavaScript debugging for ASP.NET (Chrome and IE)" option in tools\options\Debugging\General.
- Does Ctrl+F5 have the same slowness?
- Are the following repro steps correct?
Create a new Angular Web project
Run the project with F5
Stop debugging, make a change to any html or TS file
Run the project with F5

Thanks

**Comment by SteveSandersonMS** [comment] 2018-01-05 16:54
@BillHiebert I'll let @Alex-Torres answer the rest of your questions, but regarding the repro steps, that's not correct. The Angular/React/etc templates do automatic reloading, so the repro steps would be:

* Create a new Angular project using [this template](https://docs.microsoft.com/en-us/aspnet/core/spa/index), not the ones that have already shipped
* Run the project with F5 (or Ctrl+F5)
* When you see it in your browser, switch back to the IDE and save a change to one of the TS/HTML files (e.g., `ClientApp/src/app/home/home.component.html`)
* Alt-tab back to the browser to see the change automatically taking effect, but according to @Alex-Torres, the change is delayed by 5-10 seconds when you host in IISExpress compared with on Kestrel directly

**Comment by BillHiebert** [comment] 2018-01-05 16:57
@SteveSanderson Got it, thanks. If it repros with Ctrl+F5 then we can rule out script debugging or debugging in general being the culprit.

**Comment by BillHiebert** [comment] 2018-01-05 19:04
@SteveSandersonMS, @Alex-Torres - so far I have been unable to reproduce this on my development machine which is running newer VS components than what is currently available. However, I am not aware of any changes which would have affected this. 

@SteveSandersonMS - are you able to reproduce this?

**Comment by Alex-Torres** [comment] 2018-01-05 21:41
@SteveSandersonMS @BillHiebert thank you so much for taking the time to look into this.  I am attaching a video link that illustrates all the steps I took to try and replicate the problem.  Link is available [here](https://drive.google.com/file/d/1ZkQoIzX29w022qDVOJnYmRAb3cIy_HTk/view).  Please let me know if I can provide any other information that may help you guys solve this problem.

Alex

**Comment by Alex-Torres** [comment] 2018-01-13 04:35
Any updates on this?

**Comment by SteveSandersonMS** [comment] 2018-01-16 18:13
I'm afraid this is not something we've been able to reproduce. I understand @BillHiebert tried out @Alex-Torres's sample and the issue didn't occur. Also nothing like this occurs when I try it.

If you have any more information that would point to it being a specific defect in some code in the JavaSciptServices repo (as opposed to being an IIS Express issue) please let us know. Otherwise I don't think there's any action we can take on it unfortunately.

**Comment by BillHiebert** [comment] 2018-01-16 18:20
@Alex-Torres - I couldn't tell from that video but did you launch IIS Express under the debugger (F5). If so, and it launched Chrome it will run Chrome in script debugging mode (unless you disabled the script debugging option under Tools\Options\Debugging\General).

**Comment by Alex-Torres** [comment] 2018-01-18 00:28
Oh so you guys don't see the delay on the video [here](https://drive.google.com/file/d/1ZkQoIzX29w022qDVOJnYmRAb3cIy_HTk/view)?.

**Comment by MaximBalaganskiy** [comment] 2018-01-18 01:16
I cannot reproduce it anymore. Since the issue was created I upgraded VS to 15.5.3 and installed preview templates again.

**Comment by MaximBalaganskiy** [comment] 2018-01-18 01:19
I cannot reproduce it anymore - neither while debugging nor in detached mode. Since the issue was created I upgraded VS to 15.5.3 and reinstalled preview templates.

**Comment by SteveSandersonMS** [comment] 2018-01-23 17:01
Since we can't reproduce this, and since it's hard to think of any way it could be caused by any code in this repo (since code in this repo is agnostic to whether it's hosted in IISExpress vs directly in Kestrel), I'll close this. @Alex-Torres sorry if this is not satisfactory but without the ability to reproduce the issue there isn't any action we can take on it. If you do manage to find out how to reproduce the issue please let us know! Hope that's OK.

**Closed by SteveSandersonMS** 2018-01-23 17:01 UTC

**Comment by LinqBeast** [comment] 2018-01-24 01:41
I have the same issue:

https://github.com/aspnet/JavaScriptServices/issues/1489

I had to add HMR to this template btw, otherwise, I got full page refreshes.

**Comment by LinqBeast** [comment] 2018-01-24 01:48
Any reason HMR wouldn't work by default?

It seems to, in that when I save an html file, the browser refreshes, but it's a full page refresh.

**Comment by Alex-Torres** [comment] 2018-01-29 17:33
No worries.  Thank you @SteveSanderson .
