### ISSUE TITLE
[Proposal] Replace tsd.json with equivalent typings.json in templates

### ISSUE THREAD

**Issue by ClaudioNunes** [aspnet/JavaScriptServices#229] opened 2016-07-29 19:42 UTC

**Comment by MarkPieszak** [comment] 2016-07-29 20:24
Duplicate of #53.
I'll update to Typescript 2.0 and `@types` when @SteveSandersonMS gives the go-ahead. TS2 is still in beta, but types will deprecate even typings. (much easier system as well)

**Comment by SteveSandersonMS** [comment] 2016-08-04 09:00
@MarkPieszak Are you happy to do it for all the templates (not just the Angular one)? If so yes please go ahead whenever you're ready. If you prefer not to do the non-Angular ones, lets hold off until I can do them all at once, as it's advantageous just to have one common approach.

**Closed by SteveSandersonMS** 2016-08-04 09:00 UTC

**Comment by MarkPieszak** [comment] 2016-08-04 14:35
Sure I'll fix up all the templates, let me get going with that one :+1:

**Comment by MarkPieszak** [comment] 2016-08-04 17:28
@SteveSandersonMS 
Are you on Slack or anything? Tough talking on here!

I was going to say, TS2.0 is still in beta, we'll have to have some instructions on how someone can get 2.0beta setup in their environment in VSCode & VStudio, either way I can get the PR in and we can decide to hold off merging it until the official release, or get in there sooner. Whatever you want!
