### ISSUE TITLE
Unable to launch node service in debug mode

### ISSUE THREAD

**Issue by davidsekar** [aspnet/JavaScriptServices#1084] opened 2017-07-03 14:30 UTC
I'm using IIS and I couldn't launch node services in debug mode

```
public void ConfigureServices(IServiceCollection services)
    {
services.AddNodeServices(options => {
    options.LaunchWithDebugging = true;
    options.DebuggingPort = 9229;
});
}

```
Above code throws exception that the property cannot be set after completion....

Server IIS
Node version: 8

**Comment by SteveSandersonMS** [comment] 2017-07-03 15:43
Sorry for the inconvenience. Unfortunately I don't know how to reproduce the issue you're seeing. The code you've posted is not enough to get an error about "property cannot be set after completion" in my testing.

Could you please post detailed repro steps, starting with creating a new project? Thanks.

**Comment by davidsekar** [comment] 2017-07-04 05:11
I receive following error message

Looks like an issue with NodeService OutOfProc Instance initialization. (Windows 10, IIS, Node 8.x)

{System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<>c__DisplayClass24_0.<ConnectToInputOutputStreams>b__1(Object sender, DataReceivedEventArgs evt)
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__17_0(Object edi)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()}

I will try and setup a test repo.

**Comment by SteveSandersonMS** [comment] 2017-07-04 11:02
> I will try and setup a test repo.

Yes, if you can supply info that will let us reproduce this issue we can definitely make sure it's fixed (or at least the error message is clearer, if it's because of something invalid in the application or environment).

**Comment by davidsekar** [comment] 2017-07-05 05:32
Hi Steve,

Following are the steps to replicate issue

1) Clone following aspnet core angular universal repo - master branch
https://github.com/MarkPieszak/aspnetcore-angular2-universal

2) Change line number 51  of method - public void ConfigureServices(IServiceCollection services)
as 
```
 services.AddNodeServices(options => {
        options.LaunchWithDebugging = true;
        options.DebuggingPort = 42425;
      });
```
Error: 

> InvalidOperationException: The Node.js process failed to initialize: (node:6680) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.

**Comment by davidsekar** [comment] 2017-07-05 05:34
node -v
v8.1.3

OS : Windows 10

**Comment by davidsekar** [comment] 2017-07-05 05:35
Similar issue on StackOverflow
https://stackoverflow.com/questions/43825058/vs-code-running-asp-net-spa-with-angular-4-and-using-nodeservices-options-launc

**Comment by davidsekar** [comment] 2017-07-05 05:50
Issue 2:
When I update the package to
<PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="**1.1.1**" />

And run the same application, you will notice following error

> System.InvalidOperationException: 'An attempt was made to transition a task to a final state when it had already completed.'

Probable Reason:
```
app.UseWebpackDevMiddlewarenew WebpackDevMiddlewareOptions
        {
          HotModuleReplacement = true
        });
```
triggers the .net to inject a nodeservice service and it gets initialized with LaunchWithDebugging as false...

Then while triggering pre-rendering using following
```
var prerenderResult = await Prerenderer.RenderToString(
                "/",
                nodeServices,
                new JavaScriptModuleExport(applicationBasePath + "/Client/dist/main-server"),
                unencodedAbsoluteUrl,
                unencodedPathAndQuery,
                transferData, // Our simplified Request object & any other CustommData you want to send!
                30000,
                Request.PathBase.ToString()
            );
```

Then it tries to set the properties passed to AddNodeService()
```
options =>
      {
        options.LaunchWithDebugging = true;
        options.DebuggingPort = 42425;
      }
```

Resulting in 

> System.InvalidOperationException: 'An attempt was made to transition a task to a final state when it had already completed.'

**Comment by SteveSandersonMS** [comment] 2017-07-05 12:07
Aha, I see - thanks for clarifying. This was a regression caused by a change in Node.js itself between versions 6.x and 8.x, which we've since fixed in the NodeServices package code. So you have two options:

 * You could downgrade to Node 6.x which doesn't trigger this problem
 * Or, better, [upgrade to ASP.NET Core 2.0 Preview 2](https://weblog.west-wind.com/posts/2017/May/15/Upgrading-to-NET-Core-20-Preview#Upgradingto.NETCore2.0and.NETStandard2.0-mostlyeasy), which includes the latest version of NodeServices in which this fault is fixed.

**Closed by SteveSandersonMS** 2017-07-05 12:07 UTC
