### ISSUE TITLE
support VS2017rc

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#453] opened 2016-11-21 11:16 UTC
I can't open projects in VS2017 rc?

**Comment by MarkPieszak** [comment] 2016-11-21 12:50
Related issue: https://github.com/aspnet/JavaScriptServices/issues/442

**Comment by SteveSandersonMS** [comment] 2016-11-21 14:41
Closing as duplicate of #440

**Closed by SteveSandersonMS** 2016-11-21 14:41 UTC
