### ISSUE TITLE
Unable to open aspnetcore-spa project in VS 2017 RC

### ISSUE THREAD

**Issue by briannoyes** [aspnet/JavaScriptServices#515] opened 2016-12-14 16:12 UTC
Generated Angular 2 app with aspnetcore-spa generator. When I try to open the xproj file, VS 2017 RC wants to migrate the file to something:
![image](https://cloud.githubusercontent.com/assets/4534445/21189925/287f6e2e-c1ee-11e6-989e-7d0fb50f61f2.png)

But then fails in that process.
![image](https://cloud.githubusercontent.com/assets/4534445/21189910/1d80d134-c1ee-11e6-84a1-293660482d12.png)

After that, there is a .csproj in the folder that will open, but not set up to run as either a web app or as a console app.

**Comment by MarkPieszak** [comment] 2016-12-14 17:58
Duplicate of #440

**Comment by SteveSandersonMS** [comment] 2016-12-15 16:54
Yep, an update to support generating `csproj` projects is on the way imminently (it's already committed here: https://github.com/aspnet/JavaScriptServices/commit/a76b6e25d44d75f0beaa0ab42fbde673dd1b855b).

Closing this one now as duplicate; will close #440 when the updated generator is published.

**Closed by SteveSandersonMS** 2016-12-15 16:54 UTC
