### ISSUE TITLE
Update to React Hot Loader 3.0 when it ships

### ISSUE THREAD

**Issue by xabikos** [aspnet/JavaScriptServices#127] opened 2016-06-13 14:34 UTC
This is not a problem of this library but a known issue of [React Hot Loader](https://github.com/gaearon/react-hot-loader) that is used underneath. There is a plan to solve this with the new version as you can see [here](https://github.com/gaearon/react-hot-boilerplate/pull/61). I found this problem when I was trying to implement the React Redux template and just posted as some more people could face the same issue.

**Comment by SteveSandersonMS** [comment] 2016-06-13 15:07
Thanks! Have amended this issue title to specify what we're going to do.

For anyone else reading, this is a work item we'll do when https://github.com/gaearon/react-hot-boilerplate/pull/61 ships.

**Comment by SteveSandersonMS** [comment] 2016-11-07 19:59
5 months later it's not clear if or when gaearon/react-hot-boilerplate#61 will ship. Also I'm unsure what the issue is anyway - AFAIK, HMR works correctly in the ReactReduxSpa template.

I'll close this as it's not clear that there's anything we can do here. But, once React Hot Loader 3 does ship, we will update to it!

**Closed by SteveSandersonMS** 2016-11-07 19:59 UTC
Labels: enhancement, external
