### ISSUE TITLE
Registering a provider in app.module.shared does not work

### ISSUE THREAD

**Issue by ukphillips** [aspnet/JavaScriptServices#1013] opened 2017-06-05 16:56 UTC
I have an injectable service that I am attempting to register as a provider in my app.module.shared.ts, but at runtime I get the typical no provider for XXXservice error. When I move the provider registration to the app.module.client level everything seems to run fine.

**Comment by ADefWebserver** [comment] 2017-06-05 18:02
I have found that Angular services (classes decorated with @Injectable()) now need to be registered in the app.module.client.ts file.

See:
[Upgrading JavaScriptServices and PrimeNG From Angular 2 to Angular 4+ ](http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/4306/Upgrading-JavaScriptServices-and-PrimeNG-From-Angular-2-to-Angular-4.aspx)

**Comment by MarkPieszak** [comment] 2017-06-05 18:55
The shared file should actually be an NgModule itself that's imported into both client and server NgModules, that will fix that issue. As forRoot actually has to be called on a root NgModule.

**Comment by ADefWebserver** [comment] 2017-06-05 19:29
> The shared file should actually be an NgModule itself that's imported into both client and server NgModules, that will fix that issue.

Thanks @MarkPieszak, I updated my article with your directions. However, I think a lot of people will be lazy and just stick it in the client file.

**Comment by MarkPieszak** [comment] 2017-06-05 20:29
The problem is the server will error if you only include something in Client and not both platforms.

**Comment by ADefWebserver** [comment] 2017-06-05 21:19
> The problem is the server will error if you only include something in Client and not both platforms.
I never use server rendering (I use PrimeNG and as of now it doesn't support that -- I think because of components it uses). Perhaps that is why I never had problems?

**Comment by SteveSandersonMS** [comment] 2017-06-06 08:17
Thanks for letting us know. We'll need to clear this pattern up as part of fixing #986, so I'll close this issue as a duplicate of that one.

**Closed by SteveSandersonMS** 2017-06-06 08:17 UTC
