### ISSUE TITLE
Error running 

### ISSUE THREAD

**Issue by AndrewKralovec** [aspnet/JavaScriptServices#299] opened 2016-09-07 11:47 UTC
I create a asp.net core/ Angular2 application using your yo project generator. It runs fine when i run it on my computer. However, when i add it to my sever and run the  `dotnet run`  and have it on port 5000, i am unable to access it. When i run node and other projects on my server it works just fine. Which leads me to believe that there is something wrong with the project. I read a post saying that its
more likely is that your app is only binding to the localhost address (i.e. 127.0.0.1) and not the public interface. and to add     `dotnet run --server.urls=http://0.0.0.0:5000` , but when i run that i get 

 ```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/  
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method BlueWolf.Controllers.HomeController.Index (AndrewKralovec) with arguments () - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using '/home/andrew/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info: Microsoft.AspNetCore.NodeServices[0]
      Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
fail: Microsoft.AspNetCore.NodeServices[0]
      EXCEPTION: ReferenceError: localStorage is not defined
fail: Microsoft.AspNetCore.NodeServices[0]
      STACKTRACE:
fail: Microsoft.AspNetCore.NodeServices[0]
      ReferenceError: localStorage is not defined
          at LoginService.isLoggedIn (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/ClientApp/boot-server.js:1:2817)
          at Home.ngOnInit (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/ClientApp/boot-server.js:1:25440)
          at DebugAppView._View_Home_Host0.detectChangesInternal (Home.template.js:35:73)
          at DebugAppView.AppView.detectChanges (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/core/src/linker/view.js:243:14)
          at DebugAppView.detectChanges (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/core/src/linker/view.js:348:44)
          at DebugAppView.AppView.detectContentChildrenChanges (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/core/src/linker/view.js:261:19)
          at DebugAppView.AppView.detectChangesInternal (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/core/src/linker/view.js:253:14)
          at DebugAppView.AppView.detectChanges (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/core/src/linker/view.js:243:14)
          at DebugAppView.detectChanges (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/core/src/linker/view.js:348:44)
          at DebugAppView.AppView.detectViewChildrenChanges (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/core/src/linker/view.js:269:19)
        -------------   Elapsed: 3 ms; At: Wed Sep 07 2016 06:44:04 GMT-0500 (CDT)   -------------  
          at Object.Zone.longStackTraceZoneSpec.onScheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/long-stack-trace-zone.js:111:23)
          at ZoneDelegate.scheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:300:50)
          at Zone.scheduleMicroTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:237:40)
          at scheduleResolveOrReject (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:547:15)
          at resolvePromise (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:511:22)
          at /home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:493:14
          at /home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/router/src/router.js:349:17
          at ZoneDelegate.invoke (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:290:29)
        -------------   Elapsed: 2 ms; At: Wed Sep 07 2016 06:44:04 GMT-0500 (CDT)   -------------  
          at Object.Zone.longStackTraceZoneSpec.onScheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/long-stack-trace-zone.js:111:23)
          at ZoneDelegate.scheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:300:50)
          at Zone.scheduleMicroTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:237:40)
          at scheduleResolveOrReject (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:547:15)
          at resolvePromise (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:511:22)
          at SafeSubscriber._complete (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:493:14)
          at SafeSubscriber.__tryOrUnsub (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/rxjs/Subscriber.js:225:16)
          at SafeSubscriber.complete (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/rxjs/Subscriber.js:210:26)
        -------------   Elapsed: 27 ms; At: Wed Sep 07 2016 06:44:04 GMT-0500 (CDT)   -------------  
          at Object.Zone.longStackTraceZoneSpec.onScheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/long-stack-trace-zone.js:111:23)
          at ZoneDelegate.scheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:300:50)
          at Zone.scheduleMicroTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:237:40)
          at scheduleResolveOrReject (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:547:15)
          at resolvePromise (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:511:22)
          at /home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:493:14
          at SafeSubscriber._complete (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/rxjs/operator/toPromise.js:24:122)
          at SafeSubscriber.__tryOrUnsub (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/rxjs/Subscriber.js:225:16)
        -------------   Elapsed: 0 ms; At: Wed Sep 07 2016 06:44:04 GMT-0500 (CDT)   -------------  
          at Object.Zone.longStackTraceZoneSpec.onScheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/long-stack-trace-zone.js:111:23)
          at ZoneDelegate.scheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:300:50)
          at Zone.scheduleMicroTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:237:40)
          at scheduleResolveOrReject (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:547:15)
          at resolvePromise (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:511:22)
          at /home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:549:18
          at ZoneDelegate.invokeTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:323:38)
          at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/core/src/zone/ng_zone_impl.js:44:41)
        -------------   Elapsed: 0 ms; At: Wed Sep 07 2016 06:44:04 GMT-0500 (CDT)   -------------  
          at Object.Zone.longStackTraceZoneSpec.onScheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/long-stack-trace-zone.js:111:23)
          at ZoneDelegate.scheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:300:50)
          at Zone.scheduleMicroTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:237:40)
          at scheduleResolveOrReject (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:547:15)
          at resolvePromise (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:511:22)
          at /home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:549:18
          at ZoneDelegate.invokeTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:323:38)
          at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/core/src/zone/ng_zone_impl.js:44:41)
        -------------   Elapsed: 54 ms; At: Wed Sep 07 2016 06:44:04 GMT-0500 (CDT)   -------------  
          at Object.Zone.longStackTraceZoneSpec.onScheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/long-stack-trace-zone.js:111:23)
          at ZoneDelegate.scheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:300:50)
          at Zone.scheduleMicroTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:237:40)
          at scheduleResolveOrReject (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:547:15)
          at ZoneAwarePromise.then (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:625:18)
          at RuntimeCompiler.compileComponentAsync (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/compiler/src/runtime_compiler.js:50:45)
          at RuntimeCompiler.resolveComponent (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/compiler/src/runtime_compiler.js:39:21)
          at resolveComponent (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/router/src/resolve.js:35:25)
        -------------   Elapsed: 18 ms; At: Wed Sep 07 2016 06:44:04 GMT-0500 (CDT)   -------------  
          at Object.Zone.longStackTraceZoneSpec.onScheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/long-stack-trace-zone.js:111:23)
          at ZoneDelegate.scheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:300:50)
          at Zone.scheduleMicroTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:237:40)
          at scheduleResolveOrReject (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:547:15)
          at ZoneAwarePromise.then (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:625:18)
          at Router.scheduleNavigation (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/router/src/router.js:278:34)
          at Router.navigateByUrl (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/router/src/router.js:244:25)
          at Router.initialNavigation (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/router/src/router.js:140:14)
        -------------   Elapsed: 491 ms; At: Wed Sep 07 2016 06:44:04 GMT-0500 (CDT)   -------------  
          at Object.Zone.longStackTraceZoneSpec.onScheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/long-stack-trace-zone.js:111:23)
          at ZoneDelegate.scheduleTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:300:50)
          at Zone.scheduleMacroTask (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:240:40)
          at /home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:683:30
          at setTimeout (eval at createNamedFn (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/zone.js/dist/zone-node.js:1000:18), <anonymous>:3:37)
          at setupRouterInitializer (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/router/src/common_router_providers.js:39:5)
          at ReflectiveInjector_._instantiate (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/core/src/di/reflective_injector.js:698:27)
          at ReflectiveInjector_._instantiateProvider (/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/node_modules/@angular/core/src/di/reflective_injector.js:631:31)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action BlueWolf.Controllers.HomeController.Index (AndrewKralovec) in 38108.7536ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 39014.9737ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/dist/main.js?v=4n0eskTDCwzX-wG5AzFi94MrB5uBlBf1ms1dhBe3a1Q  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.js?v=vJS8eKn1wDZpNKE-SYnibVC_KjaoGWg8SWZh1HVH2iY  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/dist/vendor.js'. Physical path: '/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/wwwroot/dist/vendor.js'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/dist/main.js'. Physical path: '/home/andrew/workspace/CSharp/LinuxASP/AndrewKralovec/wwwroot/dist/main.js'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 151.1644ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 84.1983ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/images/Front.jpg  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /images/Front.jpg was not modified
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 6.0563ms 304 image/jpeg
```

How do i resolve this issue ? My project can be found [here](https://github.com/AndrewKralovec/Forecast-Report)

**Comment by MarkPieszak** [comment] 2016-09-07 11:52
Are you trying to use localStorage in your Ng2 app? I'm just noticing that referenceError.
Not sure how it would work locally any differently though, localStorage doesn't exist on the server. Hmm

**Comment by AndrewKralovec** [comment] 2016-09-07 11:53
Yeah im using localStorage on the Angular2 client side.

**Comment by AndrewKralovec** [comment] 2016-09-07 11:57
I also saw this 
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Call to Node module failed with error: To use prerendering, you must install the 'aspnet-prerendering' NPM package.
System.Exception: Call to Node module failed with error: To use prerendering, you must install the 'aspnet-prerendering' NPM package.
 
The weird thing is it runs when i just do dotnet run, but then i cant access it. So i dont know if more packages will fix this kind of error

**Comment by MarkPieszak** [comment] 2016-09-07 11:58
So unfortunately the server side doesn't know what localStorage, window, jQuery and other things don't exist on the server, you'll need to use Dependency Injection to tell both the server and browser platforms what Storage is.

Check out the code here for an example of it: https://github.com/gdi2290/ng-conf-2016-universal-patterns/tree/master/3-di-demo


Basically you need to abstract a Storage class, that the server and browser implement completely differently. Let's say Redis for the server, and localStorage for the browser in your case.

**Comment by MarkPieszak** [comment] 2016-09-07 11:59
I've had that one occur before, try clearing all node_modules, npm cache, and reinstalling. Seems that issue is a common one :(

**Comment by AndrewKralovec** [comment] 2016-09-07 12:06
Sorry, im not really an expert in asp.net. So when you so i have to create a Storage class, do you mean a c# class? Also, how would that look ?

**Comment by AndrewKralovec** [comment] 2016-09-07 12:08
Wait, i dont think this is the error. I just create a brand new project with the code gen, ran dotnet run --server.urls=http://0.0.0.0:5000, and got the same error. Local storage is deferentially not on the brand new project.

**Comment by MarkPieszak** [comment] 2016-09-07 12:10
A typescript class for Angular2, if you look at that link you can see how for the browser and server the concept of Storage is implemented then injected into each platform.
Dependency injection is a tough topic, I'm working on the Universal documentation now and will make sure to touch on this one heavily to make it as easy as I can!

**Comment by MarkPieszak** [comment] 2016-09-07 12:10
Well it looks like your package isn't installing, are you using the latest .NET Core RTM?

**Comment by AndrewKralovec** [comment] 2016-09-07 12:12
Yeah, straight from NET Core - Microsoft

**Comment by MarkPieszak** [comment] 2016-09-07 12:13
I mean the version of NET Core?

**Comment by AndrewKralovec** [comment] 2016-09-07 12:13
1.0.0-preview2-003121

**Comment by SteveSandersonMS** [comment] 2016-09-07 13:12
The error message saying you need to install `aspnet-prerendering` really does mean it. Your app is not going to run unless that module is present :)

If your app works locally but not when deployed, that suggests that some part of your deployment mechanism is failing to copy or install NPM packages. How are you deploying your app?

With whatever deployment mechanism you've chosen, make sure that *either* the `node_modules` directory is copied to the server during deployment, *or* that you run (or your deployment script does) `npm install` on the server after the rest of the app is deployed so it fetches all the `node_modules` contents.

**Comment by AndrewKralovec** [comment] 2016-09-07 16:22
I have node, dotnet, everything installed.
i do git clone https://github.com/AndrewKralovec/Forecast-Report
npm install
dotnet restore
dotnet run  // Works, but  as i said earlier i cant access it ( not bind or whatever the case)
donet run --server.urls=http://0.0.0.0:5000 // Above error
Web page shows 
```
Error.
An error occurred while processing your request.
```
How am i suppose to deploy it so it runs ?

**Comment by SteveSandersonMS** [comment] 2016-09-07 16:29
Thanks for clarifying how you're deploying it (i.e., manually).

> Works, but as i said earlier i cant access it ( not bind or whatever the case)

Does it respond when you're using a web browser that's actually running on the server (so you're remote-desktopped in (or similar) and are browsing to `http://localhost:5000`)?

Or does it only fail to respond when you're on some other machine and try to browse to `http://yourserver:5000`?

I'm asking because I'm trying to track down whether there's something special on your server that prevents processes binding to the loopback interface (if there is, this could explain it).

**Comment by AndrewKralovec** [comment] 2016-09-07 16:37
Im using a AWS ubuntu server, which is the same OS i used to create this project. So when i do dotnet run it says `Now listening on: http://localhost:50000 Application started. Press Ctrl+C to shut down`. But when go to the address on personal computer nothing is there, it says forefox cant fine it. I originally thought it was the server, which turned out not to be the chase, because i ran node.js app on the same port and that page showed up. 
So tried dotnet run --server.urls=http://0.0.0.0:5000, which gives the error and the page loads an error page 
I thought it might be because of the local storage, but when i created a new project with the code run, and i get the same thing

**Comment by SteveSandersonMS** [comment] 2016-09-07 16:44
> So tried dotnet run --server.urls=http://0.0.0.0:5000, which gives the error

OK. When you do this, what specific error do you see in the console output on the AWS machine? Presumably not the `localStorage` error because you're now talking about a fresh new project, right?

Apologies if you've already given that info (I've read back through this thread and am not sure whether you have - there are quite a few different error messages mentioned at different times).

**Comment by AndrewKralovec** [comment] 2016-09-07 16:46
No that's my bad. With my project it gives me the local storage error.
With the fesh new project it says 

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Call to Node module failed with error: To use prerendering, you must install the 'aspnet-prerendering' NPM package.
System.Exception: Call to Node module failed with error: To use prerendering, you must install the 'aspnet-prerendering' NPM package.
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.SpaServices.Prerendering.PrerenderTagHelper.<ProcessAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetCore._Views_Home_Index_cshtml.<ExecuteAsync>d__32.MoveNext() in /Views/Home/Index.cshtml:line 2
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultFilterAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllResultFiltersAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResourceFilterAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.M
```

**Comment by AndrewKralovec** [comment] 2016-09-07 16:51
This is after 
npm install
dotnet restore
dotnet run -server.urls=http://0.0.0.0:5000

**Comment by SteveSandersonMS** [comment] 2016-09-07 16:53
OK, thanks. Could you also let me know:

 * What version of Microsoft.AspNetCore.NodeServices you are using
 * If there's anything special about how Node is installed on the AWS machine that might affect its ability to locate NPM packages. For example, did you install it using `nvm` or do you have some special `NODE_PATH` env var set? Right now this is my best guess about what the issue is (i.e., something unusual about the Node installation on the AWS machine).

BTW if this particular AWS machine is just for testing and you are able to temporarily give me access to ssh into it, I would be happy to track down the issue. You could email credentials to stevesa at microsoft dot com. No worries if that's not an option - we can continue discussing here :)

**Comment by AndrewKralovec** [comment] 2016-09-07 16:57
Yeah sure, thanks for the help. I understand your time in important i appreciate your help. My email is akrala@yahoo.com, ill be seing you (stevesa@microsoft.com) an email right know with everything

**Comment by SteveSandersonMS** [comment] 2016-09-07 17:04
Great, I'll look out for the login details and will investigate tomorrow morning.

**Comment by SteveSandersonMS** [comment] 2016-09-08 14:13
For anyone else reading, Andrew and I debugged this and found it was just a deployment issue. Closing.

**Closed by SteveSandersonMS** 2016-09-08 14:13 UTC

**Comment by AndrewKralovec** [comment] 2016-09-19 04:48
Yes this issue it finally resolved. Like @SteveSandersonMS  said it was a debug issue. 
If anyone is getting routing errors try this
Make sure your sever doesnt just have the package mono-devel , but also 
the package mono-complete, this will install everything and solve any issues. 
Thanks a bunch @SteveSandersonM, you sir are awesome.
