### ISSUE TITLE
Latest version doesn't run in development mode

### ISSUE THREAD

**Issue by bmeverett** [aspnet/JavaScriptServices#729] opened 2017-03-02 18:36 UTC
I just updated to the latest version 0.8.6 and when I run `yo aspnetcore-spa` to generate a new project using React I cannot run in debug mode. This seems to be an error with a `isomorphic-fetch` and `typescript`. This may be due to the upgrade to the new typescript version. Not sure if there's anything you can do or another package has to be updated. 

![image](https://cloud.githubusercontent.com/assets/3941006/23521408/dcdfa708-ff4c-11e6-8647-2353d1cfd2e0.png)

**Comment by bmeverett** [comment] 2017-03-02 18:38
Maybe similar to #725

**Comment by SteveSandersonMS** [comment] 2017-03-07 15:23
Is this still valid? I just tried it and it worked fine. Do you have repro steps? You might need to make sure you've cleaned your NPM/Yarn cach dirs if you're still getting older packages.

I'll close this because (as mentioned) it does appear to work fine with current packages. If you can describe how to reproduce the issue on a clean machine, please let us know!

**Closed by SteveSandersonMS** 2017-03-07 15:23 UTC

**Comment by bmeverett** [comment] 2017-03-07 16:44
I get this trying to create a new project 
```
yarn cache clean
yo aspnetcore-spa
```
and selecting the react project. When yo goes to run webpack it shows the conflict types in the screenshot. 

When I run directly from the repo templates/reactspa everything runs correctly. Is the yo package not updated?

**Comment by SteveSandersonMS** [comment] 2017-03-07 17:02
Maybe `yarn cache clean` is somehow not enough to ensure you're getting the latest packages. Have you tried running `yarn upgrade` on the generated project, before running `webpack --config webpack.config.vendor.js` and `webpack`?

**Comment by SteveSandersonMS** [comment] 2017-03-07 17:05
If that doesn't work, also check that the `tsconfig.json` and `package.json` files in your generated project are the same as in the `templates/ReactSpa` project that works for you. If there's some discrepancy, it might indicate the problem (and would imply you don't have the latest `generator-aspnetcore-spa`).

**Comment by bmeverett** [comment] 2017-03-07 17:13
`yarn upgrade` and `webpack --config webpack.config.vendor.js` did it! Still get the error when creating new projects but that is probably an issue on my end. At least I know how to fix it

**Comment by bmeverett** [comment] 2017-03-07 20:51
I may have spoke too soon. `webpack --config webpack.config.vendor.js` worked but running webpack afterward still produced the same errors
