### ISSUE TITLE
Double load when opening fetch-data url with preload

### ISSUE THREAD

**Issue by utilitydelta** [aspnet/JavaScriptServices#621] opened 2017-01-29 05:38 UTC
Hi,

I noticed that the server pre-loader will load the weather forecast data via preload if the user navigates to the /fetch-data URL directly, but the browser will then re-load the data again once loaded on the client. What's the best way to stop reloading of screen data that has already been preloaded on the server?

Cheers!
Tyson

**Comment by utilitydelta** [comment] 2017-01-29 10:57
also I found that when running debug, I only get 1 load of the weather data from the service. But when deployed to azure, two loads.

**Comment by SteveSandersonMS** [comment] 2017-01-30 10:08
Which template is this - the Angular one or the ReactRedux one?

 * If you mean the Angular template, then yes, this is by design. Angular's typical approach to server-side prerendering is to do it completely separately from client-side rendering, so your application will indeed load its data once in each case. For most people that's not a problem, but if it is a problem for you, you could look at something like [Angular-Redux](https://github.com/angular-redux/ng2-redux) so that you have a clean way to transfer the server-side state to the client after prerendering, so that things are only loaded once.
* If you mean the ReactRedux template, then this should not (and does not, as far as I know) happen. Redux provides a method for transferring the server-side state to the client after prerendering, so that things are only loaded once.

I'll close this as it's working as expected, as far as I know. But please let me know if you disagree!

**Closed by SteveSandersonMS** 2017-01-30 10:08 UTC
