### ISSUE TITLE
Why need MVC for route fallback to index.html?

### ISSUE THREAD

**Issue by DibranMulder** [aspnet/JavaScriptServices#1150] opened 2017-07-26 12:33 UTC
I like to use ASP.net core because of its performance. In combination with AngularJS, because of existing legacy code purposes, its nice to serve static files at a rapid pace. Spinning up MVC doesn't add to that performance. When I use html5mode in AngularJS URLs are no longer distinguishable of AngularJS- or ASP.net core routings. 

If the routing is being handled in ASP.net core, this happens for instance when an user refreshes the browser, I want it to return the index.html page, causing AngularJS to handle the routing. But it might also be that the static file such as an assets, css file or JS library is requested it then should always return the static file if its present.

Now I can achieve this by adding the MapSpaFallbackRoute and creating an FallbackController with an Index action that returns the index.html page. Look at this:

```
app.UseMvc(routes =>
{
    routes.MapSpaFallbackRoute(
    name: "spa-fallback",
    defaults: new { controller = "Fallback", action = "Index" });
});
```

But this feel like a dirty hack. Isn't there a way to add a catch to the static files module to serve just the index.html when the requested routing could not be converted to a static file? If its not possible consider this issue as a feature request :)

**Comment by SteveSandersonMS** [comment] 2017-07-27 10:55
> Isn't there a way to add a catch to the static files module to serve just the index.html when the requested routing could not be converted to a static file?

That is precisely what `MapSpaFallbackRoute` does. I'm sorry if I'm misunderstanding the request - if you could clarify what different functionality you're looking for, we could consider the request.

I'll close this as by design for now.

**Closed by SteveSandersonMS** 2017-07-27 10:55 UTC

**Comment by SteveSandersonMS** [comment] 2017-07-27 14:37
Oh I think I see what you mean - you want this to be more low-level middleware, not relying on MVC routing.

This might become possible in the future, as we're considering moving routing to be a more standalone middleware, separate from MVC. If that does happen we might do what you're asking for!

**Comment by DibranMulder** [comment] 2017-07-28 09:38
Yeah that's exactly what I mean! I don't see how routing is tied to MVC, it should be a stand alone middleware feature.

**Comment by naegelejd** [comment] 2018-05-30 18:31
To be clear, this means I can't really use the SPA fallback features without `app.UseMvc(...)`?

I am new to ASP.NET and I've inherited a working application that hosts a REST API. I do not enable MVC, but I do enable Routing: `services.AddRouting()` and `app.UseRouter(...)`, where my RouteBuilder defines routes like this:

`routeBuilder.MapGet("/api/status", httpCtx => { ... } );`

All routes are under the `/api/` parent path.

How can I host an SPA from within my content root using this approach? I don't yet need any fancy features like server-side rendering or webpack compatibility, I just want to host my `index.html` which loads a React application from a folder in the same content root, but I don't want it to conflict with my `/api/` routing.
