### ISSUE TITLE
Update to Typescript 2.0.x in template projects

### ISSUE THREAD

**Issue by emzero** [aspnet/JavaScriptServices#342] opened 2016-09-30 01:22 UTC
Update to Typescript 2.0 in template projects

Also, remove tsd in favor of new TS 2.0 @types packages.

**Comment by MarkPieszak** [comment] 2016-09-30 20:11
PR #258 
It'll all be in there once we get the ReactRedux issues fixed due to the upgrade.

**Comment by SteveSandersonMS** [comment] 2016-10-05 14:26
Yep, we will do this. I'll close this issue as a duplicate of #258.

**Closed by SteveSandersonMS** 2016-10-05 14:26 UTC

**Comment by MarkPieszak** [comment] 2016-10-05 14:39
@SteveSandersonMS I'm closing out my existing TS2 PR for a new one that's updated, and has everything working I'll be done in about 10minutes!

Got ReactRedux working as well, and updated everything to reflect recent changes (main-server renames etc)
