### ISSUE TITLE
WebpackDevMiddleware does not work with async webpack config (with promises)

### ISSUE THREAD

**Issue by Sky4CE** [aspnet/JavaScriptServices#1399] opened 2017-11-30 15:54 UTC
I have webpack config in my project configured in a way that it exports promise:
`module.exports = commonConfigPromise`
this is need as I do async(IO) operations during config. It works fine when I build project using npm, but it fails when aspnet build it using WebpackDevMiddleware with this error:
![image](https://user-images.githubusercontent.com/9821633/33439954-6f0b2aae-d5f7-11e7-8131-5d556764d9fd.png)

**Comment by SteveSandersonMS** [comment] 2017-11-30 16:32
Duplicate of #907

**Closed by SteveSandersonMS** 2017-11-30 16:32 UTC
