### ISSUE TITLE
Visual Studio reverts changes

### ISSUE THREAD

**Issue by ManuelDeLeon** [aspnet/JavaScriptServices#136] opened 2016-06-15 17:18 UTC
This happens in dev & prod modes. To reproduce:

1. Create an Angular 2 project
1. Open the `.xproj` file with Visual Studio (I'm using 2015)
1. Kick off `dotnet run`
1. Open `http://localhost:5000` on a browser (preferably Chrome as it tends to work better with HMR).
1. Using Visual Studio modify a file, say `home.html` from `Hello, World` to `Hello, Everyone`

Now 2 things will happen. 

1. HMR does't work.
1. When you refresh the page it will flash `Hello, Everyone` for a split of a sec and then go back to `Hello, World`
1. If you restart the server (on the console) and refresh the page you'll get the right value; but then further changes are discarded (as before).

This doesn't happen if you use Visual Studio Code (or any other editor for that matter). So if you close Visual Studio, terminate the server on the console, start the server again (`dotnet run`), open the page on Chrome, and then modify `home.html`, HMR works (the page is immediately updated) and refreshing the page will display the right text.

Any ideas why Visual Studio is messing things up?

**Comment by doczoidberg** [comment] 2016-06-17 11:12
same problem here

**Comment by laskoviymishka** [comment] 2016-06-17 13:36
Please check your ASPNET_ENVIRONMENT
From console you run it as `Prod` by default.

**Comment by ManuelDeLeon** [comment] 2016-06-17 13:57
It happens with the env variable in both Development and Production.
Remember that it only happens when VS is open. The problem goes away as
soon as I close VS.

**Comment by laskoviymishka** [comment] 2016-06-17 14:05
@ManuelDeLeon what if you run you app from visual studio, but not under iis express? Does it still reproduced?

**Comment by ManuelDeLeon** [comment] 2016-06-18 23:00
How do you run the app from visual studio but not iis express?

Either way I don't know why it matters as it happens just by having VS open. That is if I run `dotnet run`, open the .xproj in Visual Studio, and then modify a file with notepad.

**Comment by SteveSandersonMS** [comment] 2016-06-21 10:16
I'm afraid I can't repro this. I followed your repro steps, but it worked correctly: HMR *did* work, and the server and client-rendered versions of the app correctly reflected my changes.

Is it possible you've got some VS add-in or extension that interferes? Perhaps some kind of "webpack" or other client-side helper add-in?

I'm running "Visual Studio 14.0.5123.00 Update 2" (according to the *About* dialog) and have installed absolutely no add-ins etc. beyond what the original VS installer put there.

**Comment by doczoidberg** [comment] 2016-06-21 10:37
can't test at the moment. maybe web essentials?

**Comment by MarkPieszak** [comment] 2016-06-21 18:54
It could be that doc, that one has given me problems in the past with numerous things as well. Give it a shot.

**Comment by SteveSandersonMS** [comment] 2016-06-30 15:33
Closing since the conversation appears to have ended, but if anyone can still repro this and can give details, please reopen or file a new issue.

**Closed by SteveSandersonMS** 2016-06-30 15:33 UTC
Labels: bug, waiting
