### ISSUE TITLE
Hot module loading doesn't work

### ISSUE THREAD

**Issue by jtheisen** [aspnet/JavaScriptServices#1608] opened 2018-04-13 16:51 UTC
I did

```
dotnet new react test
cd test
npm i
dotnet restore
dotnet run
```

The app displays fine in the browser, but changes in the source files are not reflected.

I do see the build being triggered by a change, and I do get these lines in the browser console after each build:

```
[HMR] bundle rebuilding
[HMR] bundle rebuilt in 47ms
```

But any text change I make is still not updated.

This used to work when I tried one or two months ago, but I

- don't know which version of the template it was and
- don't know how to specify the template version in `dotnet new`.

Not sure if this is related to #1585.

**Comment by bastienJS** [comment] 2018-04-18 18:43
I also did dotnet new react, rebuilt in VS2017 , started it and changed html or text. All I get is a cheap... browser refresh not HMR at all!

**Comment by ADefWebserver** [comment] 2018-04-18 20:29
@bastienJS  - Yes the lack of HMR was a deal breaker for me.

**Comment by SteveSandersonMS** [comment] 2018-05-17 13:47
@Vx2gas Yes that is the case. If you wanted a different form of HMR you'd have to check Angular CLI docs to see what other options might exist, since HMR is entirely provided by Angular CLI if you're using that template.

**Comment by SteveSandersonMS** [comment] 2018-05-29 10:51
If anyone has specific repro steps (for the HMR-not-responding-to-changes issue), please let us know. In the meantime I'll close this because without any repro steps it's not something we have a way of investigating.

**Closed by SteveSandersonMS** 2018-05-29 10:51 UTC

**Comment by jtheisen** [comment] 2018-05-29 12:55
What more than the steps I posted do you need?

**Comment by SteveSandersonMS** [comment] 2018-05-29 13:03
Sorry for the inconvenience, but to investigate I'd need steps that reproduce the issue on a clean machine. The steps posted above don't, as in general `dotnet new react` produces a project with working HMR. You may want to update your machine to the latest ASP.NET Core 2.1 release - you'll probably find that you no longer have any issue if so.

**Comment by jtheisen** [comment] 2018-05-29 13:41
It does indeed work now with 2.1, thanks.
