### ISSUE TITLE
AutoMapper fails to install

### ISSUE THREAD

**Issue by ergodaveh** [aspnet/JavaScriptServices#341] opened 2016-09-29 20:07 UTC
Just tried these Steps today:
To run the samples:
    Clone this repo
    At the repo's root directory (the one containing src, samples, etc.), run dotnet restore
***  the AutoMapper fails to install  ***
    Change directory to the sample you want to run (e.g., cd samples/angular/MusicStore)
     etc...

the log entry:
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://go.microsoft.com/fwlink/?LinkID=230477/FindPackagesById()?id='AutoMapper''.
log  : The content at 'https://go.microsoft.com/fwlink/?LinkID=230477/FindPackagesById()?id='AutoMapper'' is not valid XML.
log  :   For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.

Cheers

**Comment by SteveSandersonMS** [comment] 2016-09-30 16:18
I just cleared my package cache and tried `dotnet restore` for this, and it worked OK (AutoMapper was found and installed properly). Maybe there was a temporary network issue when you tried - I'd suggest trying again (and if necessary, clearing your dotnet package cache first - it's probably in your user directory under `.nuget/packages`).

Closing as can't repro, but if you still think there's an issue, please let us know.

**Closed by SteveSandersonMS** 2016-09-30 16:18 UTC

**Comment by ergodaveh** [comment] 2016-09-30 19:56
Thanks for looking into this issue.  I have used your method of removing the cache using 'nuget locals all -clear' and attempt the 'dotnet restore' again without success.   being generally more comfortable in VS.   I have opened the project/solution within VS2015 and tried to build the solution.   VS returned the same failure. Such that I tried the PM approach to add the latest resource available..    Tried another build and VS suggested Microsoft.Tpl.DataFlow was needed..  PM'd the latest into the solution and attempted another Solution Build.   This time the error suggests the latest version of AutoMapper excludes the method  Mapper.CreateMap<...etc).  Afterwards <uninstall and installing AutoMapper 4.2 and a Clean Solution>  the Solution builds.   
Returning the 'dotnet restore' Step...  again fails to complete.
Cheers,

**Comment by SteveSandersonMS** [comment] 2016-10-05 10:30
Sorry, I don't know why you're having this issue, but I've confirmed on a couple of other machines that the project is set up to build correctly. Maybe you have some custom NuGet feed or are running a special build of .NET. Beyond that, I'm afraid I'm not sure what the issue is. If you are keen to dig into this further, you might want try making a minimal repro project (see how much you can strip out of the `samples/angular/MusicStore` while the error remains) and report it to [NuGet](https://github.com/NuGet/Home).

**Comment by TylerJGabb** [comment] 2018-07-23 19:50
I am having this issue with a brand new vanilla console project.
