### ISSUE TITLE
Opening generated .csproj freezes VS2017

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/JavaScriptServices#1139] opened 2017-07-21 03:55 UTC
_From @kakins on June 16, 2017 23:43_

I have VS2017 (latest update as of today).

I did the following

1. dotnet new --install Microsoft.AspNetCore.SpaTemplates::*
2. dotnet new angular
3. Opened the generated .csproj in VS2017.

VS2017 freezes indefinitely.

However, I did notice that the .csproj opens if I do "dotnet restore" and "npm install -d" after creating the angular project.  Perhaps Visual Studio is freezing when trying to resolve all the dependencies?  That seems odd though.  At this point I'm not sure if it's a VS issue or not.

_Copied from original issue: dotnet/templating#962_

**Comment by mlorbetske** [comment] 2017-07-21 03:55
_From @seancpeters on June 17, 2017 0:49_

Hi @kakins,
Could you run the command `dotnet --info` and paste the output here?
Also, could you post the exact version of VS you're running, from help > about?

That info will help us troubleshoot your issue. Thanks!

**Comment by mlorbetske** [comment] 2017-07-21 03:55
_From @kakins on June 17, 2017 1:12_

Sure thing...

# VS #
Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.13) Release
VisualStudio.15.Release/15.2.0+26430.13

# dotnet #
Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

**Comment by mlorbetske** [comment] 2017-07-21 03:56
cc @SteveSandersonMS

**Comment by SteveSandersonMS** [comment] 2017-07-27 12:03
There might be a VS issue in older versions of VS to do with restoring dependencies, but I haven't been able to reproduce any such issue. It certainly works OK in the latest VS 15.3.0 Preview 5.

Since there's a workaround (pre-restoring the dependencies), it's not been reported by others, and it doesn't appear to be an active issue in the forthcoming version of the product, there probably isn't anything for us to do on this, so I'll close it. If we find a repro or get more reports we can reconsider.

**Closed by SteveSandersonMS** 2017-07-27 12:03 UTC
