### ISSUE TITLE
Problem with Hot Reloading

### ISSUE THREAD

**Issue by Tomk77** [aspnet/JavaScriptServices#738] opened 2017-03-06 16:03 UTC
Hi,

Hot reloading isn't always reloading the changes I make to my code, but it only seems to go wrong when I'm nesting routes.

My routing:

```
<Route component={Layout}>
        <Route path='/' component={AccessWrapper}>
            <Route path='/login' component={Login} />
        </Route>
    </Route>
```

When I navigate to / and change something it reloads fine.

When I nagivate to /login and change the exact same thing I just changed it doesn't reload anymore, none of the changes make the page reload when I'm on the /login page.

Could you tell me what I'm doing wrong?

**Comment by SteveSandersonMS** [comment] 2017-03-07 14:46
Strange. I wasn't able to reproduce this. I started with a default new React project, and changed the route config to this:

```
export default <Route component={ Layout }>
    <Route path='/'>
        <Route path='/counter' components={{ body: Counter }} />
    </Route>
    <Route path='/fetchdata' components={{ body: FetchData }} />
</Route>;
```

Then I went to the `/counter` page, and edited the source (`Counter.tsx`). HMR worked correctly and the change showed up.

If you have repro steps and reason to believe the problem is with some of the code in this repo (JavaScriptServices), please let us know! Until then I'll close this as it's not something I can repro and it doesn't sound like the issue would be here. Hope that's OK!

**Closed by SteveSandersonMS** 2017-03-07 14:46 UTC
