### ISSUE TITLE
Cannot get HMR to work with the ASP.NET Core Angular 2 Template in Visual Studio Code for MAC

### ISSUE THREAD

**Issue by shima20** [aspnet/JavaScriptServices#419] opened 2016-11-05 21:23 UTC
I followed this blog http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/ to create a project in VS 2015.  In trying to use this same project in Visual Studio Code for MAC, I cannot get HMR to work.  I worked with @MarkPieszak to get the page to launch through the debugger, however, everytime I make a change to an html file, nothing happens.  It also never says "HMR Connected" and only shows "Node will restart because file changed".

**Comment by marcelush** [comment] 2016-11-05 23:08
Have you setup your running environment to Development?

**Comment by shima20** [comment] 2016-11-05 23:41
Yes I did do that but I think you can just start it through vs code

**Comment by marcelush** [comment] 2016-11-05 23:53
yes, you can on launch arguments.

that was my usual mistake, was trying to see if it could be the obvious first time mistake when HMR is not on

if application says on startup `hosting env: Development` then it's good on that point

**Comment by SteveSandersonMS** [comment] 2016-11-07 17:02
Are you saying that HMR works if you run `dotnet run` from a command prompt, but doesn't when you launch your ASP.NET app from VS Code somehow?

If so, then the issue must be to do with how you're launching it from VS Code. Could you provide some info that would allow us to reproduce your scenario? How exactly are you launching it from VS Code? Is there a particular `launch.json` config you're using?

**Comment by shima20** [comment] 2016-11-07 17:08
It runs fine in VS 2015 but when I moved to VS Code HMR didn't work.  Here is my launch.json file.

`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/netcoreapp1.0/Transfer.Web.dll",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceRoot}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command.pickProcess}"
        }
    ]
}`

**Comment by shima20** [comment] 2016-11-07 17:37
Here is my tasks.json file as well.

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "dotnet",
    "isShellCommand": true,
    "args": [],
    "tasks":[{
        "taskName": "build",
        "args": ["${workspaceRoot}//project.json"],
        "isBuildCommand": true,
        "problemMatcher": "$msCompile"
    }]
}
```

**Comment by SteveSandersonMS** [comment] 2016-11-07 18:28
Sorry, I still haven't been able to reproduce the issue. I tried configuring VS Code to launch the app in the same way, but HMR is working fine for me.

Is there any other info you can provide that would help us to reproduce the issue?

**Comment by shima20** [comment] 2016-11-07 18:56
@SteveSandersonMS  is it possible that webpack is not working correctly on my MAC?  When I debug, it never rebuilds the webpack js files unless I run "webpack" in the terminal.

**Comment by SteveSandersonMS** [comment] 2016-11-07 18:59
It sounds like you're running in production mode (like @marcelush commented before). That would explain why it only rebuilds the `wwwroot/dist` files when you run `webpack` manually, and why you don't have HMR.

However it *should* be in development mode because your config contains `"ASPNETCORE_ENVIRONMENT": "Development"`. I don't know why it's running in production mode if you are using that config file. That's what I'd need to be able to reproduce!

In the meantime, I suggest you just launch your project from the command line (i.e., run `export ASPNETCORE_Environment=Development` and then `dotnet watch run`).

**Comment by shima20** [comment] 2016-11-07 19:04
Hmm, I ran those commands and saw this...

`
npm WARN webpack-dev-server@1.16.2 requires a peer of webpack@>=1.3.0 <3 but none was installed.
npm WARN webpack-dev-middleware@1.8.4 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.
`

**Comment by SteveSandersonMS** [comment] 2016-11-07 19:08
I don't know why you get those warnings either, but you should try deleting your `node_modules` directory and recreating it (by running `npm install`). Maybe when you transferred the project to the mac, the `node_modules` did not get copied across correctly.

**Comment by shima20** [comment] 2016-11-07 19:12
Actually, when moved everything, I didn't have a node_modules folder and @MarkPieszak helped me with that part of it.

I'm also seeing this... Is this anything?

`
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8

npm ERR! missing script: start
`
`
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server:dev:hmr"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
`
npm ERR! missing script: server:dev:hmr

**Comment by SteveSandersonMS** [comment] 2016-11-07 19:18
I don't know what any of that stuff would be caused by. It doesn't look related to the Angular2Spa template :(

Your project seems to be in quite a messed-up state. It's probably best if you look at recreating it and copying across just the parts that you created.

**Comment by shima20** [comment] 2016-11-07 19:22
Okay, I will try that and see what happens.  For future reference, is there any specific directions for MAC on what to install etc or how the launch.json and tasks.json are supposed to be set up for when using this template?

It's just weird that it works on one and not the other...

**Comment by SteveSandersonMS** [comment] 2016-11-07 19:25
In general it works the same on Mac as on Windows. If you manage to find a problem with repro steps please let us know! I'll close this as it looks like we've explored all the possibilities now. Thanks.

**Closed by SteveSandersonMS** 2016-11-07 19:25 UTC

**Comment by shima20** [comment] 2016-11-07 22:30
So I created a new project and moved everything over to VS Code (including `node_modules`) and HMR worked.  Then, I created another project and moved everything BUT `node_modules` and then generated it on the VS Code side via `npm install`, it didn't work again.  Not sure if this is the catalyst or not.

**Comment by rekhasfahrizi** [comment] 2017-03-17 02:13
i have same problem,
but in my case the text "[HMR] connected" in browser is running well, when i try to changes HTML file and save it, nothing happened

did i miss something?

Thank

**Comment by nbayles05** [comment] 2017-04-21 23:03
Check the project properties dialog under the Debug settings.  There is an "Environment Variables" section.  Make sure the ASPNETCORE_ENVIRONMENT is set to Development.
![environment](https://cloud.githubusercontent.com/assets/1083950/25298670/622aebd2-26b4-11e7-84ee-74c323b927ac.jpg)
