### ISSUE TITLE
Exception: Call to Node module failed with error: To use prerendering, you must install the 'aspnet-prerendering' NPM package.

### ISSUE THREAD

**Issue by MarkPieszak** [aspnet/JavaScriptServices#144] opened 2016-06-21 19:27 UTC
Tried a fresh install from the yeoman generator today, and even after running `npm i` (the node_modules folder isn't empty, everything is definitely installed) and `dotnet restore`, when loading up `localhost:5000` it shows an internal server error right away. Windows 7 PC. (I have no issues on a separate MAC)

Also, strangely Visual Studio thinks that the dependencies weren't installed:
![image](https://cloud.githubusercontent.com/assets/2574412/16243292/8ab8425a-37c4-11e6-9f4f-c202731aa5a7.png)

![image](https://cloud.githubusercontent.com/assets/2574412/16243314/a5ab1bc8-37c4-11e6-8f5e-cb03de612d22.png)

-------

When running with F5 through Visual Studio it breaks here, and throws a similar error: *Call to Node module failed with error: To use webpack dev middleware, you must install the 'aspnet-webpack' NPM package*

![image](https://cloud.githubusercontent.com/assets/2574412/16245132/6c5d2b8c-37cd-11e6-9477-33fd761edd61.png)

**Comment by SteveSandersonMS** [comment] 2016-06-22 12:39
A known issue in VS 2015 Update 2 (and all prior versions) is that it can't correctly restore NPM packages such as the Angular 2 ones due to path length limitations on Windows, and the fact that it uses NPM 2.x instead of NPM 3.x which solves the problem. If VS has been involved in trying to restore your NPM packages, then it's likely that your `node_modules` is in a bad state, and that will probably explain why `aspnet-prerendering` was not installed. BTW you can check whether it was installed by looking in the `node_modules\aspnet-prerendering` folder, which I'm guessing won't existing in your project, or if it does, may contain an incomplete set of files.

If you're using Angular 2 and VS, your options are:
 * Don't use VS to restore NPM packages. Always do it exclusively from the command line, and if VS has interfered, be sure to delete `node_modules` completely before running `npm install` on the command line again.
 * Or, reconfigure your copy of VS to use NPM 3.x (see the earlier discussion at https://github.com/aspnet/JavaScriptServices/issues/119)

The VS team is aware of the need to upgrade to NPM 3.x by default, and I believe has a fix coming not too long from now.

Also, I just checked on a Windows machine that the latest `generator-aspnetcore-spa` templates for Angular 2 does work OK, including when you launch it from VS, assuming the NPM modules were restored correctly. So I'll close this, but please reopen if you still think there's a bug (beside the VS limitation).

**Closed by SteveSandersonMS** 2016-06-22 12:39 UTC

**Comment by MarkPieszak** [comment] 2016-06-22 15:59
Thanks for your response Steve! So I'm running the latest Node 6x NPM 3x, and the issue still happens even when I closed down Visual Studio, `rimraf node_modules` then `npm i` then `dotnet run`.

The module is definitely there as well, very bizarre.

![image](https://cloud.githubusercontent.com/assets/2574412/16273672/7ce5bce6-3870-11e6-9ae4-1767ab07c99f.png)

**Comment by SteveSandersonMS** [comment] 2016-06-22 17:02
If there files are definitely in the right place on disk, I'd have to guess that Node is looking for them in the wrong place. There are various ways of configuring where Node finds modules. Or, it might even be possible to launch your app in such a way that the current working directory is something other than the project root, and then the Node instance would look for `node_modules` relative to the wrong dir.

I'd need to be able to repro this to investigate. So if you have a minimal project that causes the issue, and can post it online somewhere, please let me know. Or if you're able to debug and track down the fault, also please reopen the issue and post details so we can try to be more resilient against whatever condition your app is in.

**Comment by joff1979** [comment] 2016-07-14 12:11
I am having this exact same issue. I am using the Angular Yeoman Template. All NPM Packages have installed correctly and when I use dot net run I get -

> Call to Node module failed with error: To use prerendering, you must install the 'aspnet-prerendering' NPM package.

When I open up in VS2015 and run from there I get 

> Call to Node module failed with error: To use webpack dev middleware, you must install the 'aspnet-webpack' NPM package

Unfortunately I cannot load this to Github for you to view from work but I will try it out at home to see if it is an environmental issue tonight. If I get the same problem I will save the repro.

**Comment by joff1979** [comment] 2016-07-14 16:55
OK so have tested this on my home PC and everything works as expected.  (Win 10, Latest Node and NPM)

So this issue is specific to my enviroment at work (Win 7 behind corporate firewall).  Not sure where to start in resolving this. Any tips ?

I have tried uninstalling/reinstalling Node,  setting the node enviroment path and reinstalling all the various components without any luck.

**Comment by joff1979** [comment] 2016-07-15 10:22
I think I am edging towards a resolution. By editing the source code for SPAServices and adding __dirName to the prerendering error message I was able to establish that Node is running in the User\AppData\Local\Temp Directory when running this app. 

So I figured this was why node could not require the npm package. If I copy my Node Modules to that folder I get further, the prerender is found and instead get some errors with vendor.js and main.js.  However I suspect that this is more due to my configuration issues than a problem with the code itself. Here is the error detail -

> Exception: Call to Node module failed with error: ReferenceError: vendor_99144b2b8400b60c2dc0 is not defined
at Object.<anonymous> (<anonymous>:1:1718)
at __webpack_require__ (<anonymous>:1:339)
at Object.module.exports (<anonymous>:1:1651)
at __webpack_require__ (<anonymous>:1:339)
at Object.<anonymous> (<anonymous>:1:1156)
at __webpack_require__ (<anonymous>:1:339)
at config.directives (<anonymous>:1:559)
at Object.<anonymous> (<anonymous>:1:582)
at Module._compile (module.js:541:32)
at requireFromString (C:\Users\xxx\AppData\Local\Temp\node_modules\require-from-string\index.js:27:4)


I have been looking around for ways to fix my Node configuration but am not having much luck. I have uninstalled and reinstalled several times, removed NODE_PATH etc. without any joy. 

I'm guessing there must be a setting somewhere that is causing node to behave strangely.  I will keep you posted.

**Comment by aggrojus** [comment] 2016-07-15 13:24
I got that exact error message when I installed aspnet-prerendering and aspnet-webpack globally ... That was before I did all uninstall.  Let me know if you determine the root issue with your environment.  My solution didn't explain the root issue for me.

**Comment by joff1979** [comment] 2016-07-15 15:41
Ok So it is working now.  I had one more stab at reinstalling Node. 

This time I -

- Cleared all npm and node related temp files from User\AppData\Local\Temp, 
- Also removed NPM and NPM Cache from Roaming (Which I had done before) 
- Removed NODE PATH from Environment Variables
- Uninstalled Node
- Rebooted
- Installed node
- Installed webpack globally - That is it no other pakages
- Then ran the project (not Expecting it to run) using dotnet run from the command line . And it worked!

Hope this helps someone.

**Comment by MarkPieszak** [comment] 2016-07-15 16:10
nicely done Joff :)

**Comment by yehia2amer** [comment] 2016-07-20 14:03
i just removed webpack using `npm uninstall -g webpack`
and used aspnet-webpack insted `npm install -g aspnet-webpack`
and Now everything is working fine !

**Comment by MarkPieszak** [comment] 2016-07-21 14:59
One of my Win7 (64bit) PCs was also having this issue, but I was using `nvm` (node version manager for windows), I ended up uninstalling that, uninstalling Node (clearing appdata cache for node/npm etc) Re-installing 6.3 normally, and strangely enough the issue is still there. **But** the project is able to run on that machine. At this point I have no idea what's causing it :)

![image](https://cloud.githubusercontent.com/assets/2574412/17027542/35446cb0-4f32-11e6-9869-fe3a86b5116e.png)


The project successfully runs so that's good enough!

Just putting this info out there incase anyone else runs into these issues.

**Comment by SyntonicStudios** [comment] 2016-07-24 21:07
I have tried every single suggestion here and no matter what I do or how I try running this app, I get "Exception: Call to Node module failed with error: To use prerendering, you must install the 'aspnet-prerendering' NPM package." every single time. 

I have the absolute newest, cleanest install of node and npm. I have never used Visual Studio to run npm install or even run the app. I followed all the directions down to the single letter. aspnet-webpack is clearly installed and has all of its files. 

The only way I can get this to run is to kill off all attributes in <app> in index.cshtml, which I'm pretty sure is going to kill off hot loading. 

I'm on Windows 10 if that matters.

**Comment by MarkPieszak** [comment] 2016-07-25 01:36
@SyntonicStudios Are you using node version manager or anything? Suspected that might of been my problem. I removed node completely and deleted all those folders, installed from scratch, semi works on one machine, fine on the other. Strange.

**Comment by chris-herring** [comment] 2016-07-25 10:34
Strange indeed. I'm running win 10 and using nvm and have had no issues with aspnet-prerending.

@SyntonicStudios have you checked that aspnet-prerending exists in the node_modules folder? What project are you running up, one of the templates?

**Comment by SyntonicStudios** [comment] 2016-07-25 13:52
I have never used the node version manager and I did indeed verify that the aspnet-prerendering was populated in the node_modules folder.

I just tried this on my work machine and am getting a completely different error running from VS2015:
System.ComponentModel.Win32Exception
The system cannot find the file specified
at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.LaunchNodeProcess(string entryPointFilename, string projectPath, string commandLineArguments)
at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance..ctor(string entryPointScript, string projectPath, String[] watchFileExtensions, string commandLineArguments)

At work running it from dotnet run seems to work, but the hot reloading doesn't seem to be working properly. It just gives me a flash of the updated content and then quickly reverts to the old stuff. Weird. 

I'm afraid this entire setup is just too brittle to be used for me. This is a shame because getting Angular 2 with TypeScript working properly in the same project as ASP.NET Core is bizarrely difficult right now.

**Comment by MarkPieszak** [comment] 2016-07-25 14:02
Have you tried globally installing webpack and also aspnet-webpack?
What version of Node, Typescript do you have?

Have you done an npm cache clean complete node_modules folder wipe, and reinstall / restore packages? @SyntonicStudios 

Brittle indeed, it'll get better soon!

**Comment by tinchou** [comment] 2016-07-28 20:59
My project was working fine, and now I'm facing this issue. Can't remember any change I made that would've triggered this!

I'm using node v6.3.1.

**Comment by MarkPieszak** [comment] 2016-07-28 21:26
@tinchou did you install nvm or anything and have multiple nodes running / anything like that?

It is strange it keeps cropping up even after RTM was released. I need to look into what the real issue is that's causing this, but looks like everyone has different reasons.

Try completely deleting node_modules and Restore Packages among other things. 
A complete wipe of Node and all related AppData cache node and npm files, and removing Node from path etc, reinstalling worked on 1 PC I had it on.

@SteveSandersonMS What can we log this issue to in terms of aspnet? Seems to be around post rc2 (even with Npm3+)

**Comment by tinchou** [comment] 2016-07-28 21:34
It's working now.

I had chakracore, node 6 and node 4. I followed all instructions [here](https://github.com/aspnet/JavaScriptServices/issues/144#issuecomment-232784511) except for uninstalling the ones I wasn't using (it wasn't on the path, so it shouldn't affect, right?).

That didn't work, so I uninstalled, cleaned again, rebooted, and it worked.

**Comment by tinchou** [comment] 2016-09-20 20:47
And this just happened again when I switched from Node 5.X to Node 6.5.0 in Azure through the application settings configuration.

I went into Kudu and cleaned the environment with these commands:

```cmd
cd D:\home\site\repository
git clean -xdf
cd ${env:APPDATA}
rm -r npm-cache
rm -r npm
```

Then I deployed my app again without success. Any ideas how to better clean my App Service environment?

**Comment by SteveSandersonMS** [comment] 2016-09-20 21:24
I'm not sure what effect this "cleaning" process would have, but if you have access to a command-line interface on your server, can you check that the `webpack` and `aspnet-prerendering` packages are really there?

```
cd yourapproot
dir node_modules    [see if 'webpack' and 'aspnet-prerendering' are in the output]
```

... and perhaps more importantly:

```
node -e "require('aspnet-webpack')"
```

This may return useful error information if there's some problem loading the `aspnet-webpack` module. Please let us know what you find.

**Comment by SteveSandersonMS** [comment] 2016-09-20 21:34
And can you just confirm that it's definitely complaining about the absence of `aspnet-prerendering`, and *not* about `aspnet-webpack`?

**Comment by tinchou** [comment] 2016-09-20 22:39
I'm using Azure App Service, and it's a managed service. I get an online console through Kudu at https://{{project}}.scm.azurewebsites.net/DebugConsole/?shell=powershell, but I don't have admin access.

Anyway,

1. All packages are there
2. Requiring both `aspnet-prerendering` and `aspnet-webpack` from the console as you suggested works fine
3. The error that I'm getting in my logger (Application Insights) is: `Call to Node module failed with error: To use prerendering, you must install the 'aspnet-prerendering' NPM package.`
4. Here is the call stack in case you find it useful: https://gist.github.com/tinchou/48e77c5ab73c2f2e12a3a7a6df3e65ec

Thanks!

**Comment by SteveSandersonMS** [comment] 2016-09-21 10:49
I've published updated versions of `Microsoft.AspNetCore.SpaServices`, `aspnet-webpack`, and `aspnet-prerendering` that return more debugging information in these cases. They will now tell you the underlying error that came back from Node, plus the current directory your app is running in, so you can verify that the packages are in `thatdirectory/node_modules`.

Can you update to the latest versions of all of these and see if the extra info it gives will help you identify the cause?

**Comment by tinchou** [comment] 2016-09-21 13:33
This is good and sucks at the same time: after upgrading these packages, it's working. So I can't give you debug information, but hopefully the next person will :).

**Comment by sohaibjaved44** [comment] 2017-02-15 14:10
Hey I'm new to angular2 and facing the same problem, I finally have  removed "asp-prerender-module " attribute from my <app></app> tags to make my 3rd party tool primeNg work. 
I could not figure out the reason behind the error "Event not found" same happened with another 3rd party node module too.
Something wrong with pre-rendering module I guess?
has it been fixed ?
and unfortunately it takes 5 minutes to render my UI in development. is it this slow?

**Comment by shaban01** [comment] 2017-02-20 12:03
Remove contents of folder "C:\Users\<your user>\ node_modules/ "

**Comment by derricksimpson** [comment] 2017-02-20 19:44
@sohaibjaved44 this is primarily related to primeng's use of "Event", which does not exist on the server.  I use PrimeNG with this template for an internal tool - without any server-side rendering - and it the application is definitely not slow. The initial view is displayed within a few seconds.
