### ISSUE TITLE
Upgrading to version 2.0.1 fails

### ISSUE THREAD

**Issue by shaunrfield** [aspnet/JavaScriptServices#1069] opened 2017-06-27 04:58 UTC
We have this package include as a devDependencies.  Whilst it doesn't cause npm install to fail the error in the output causes our dotnet build break.  You can easily replicate the issue by running the install just for this package -

Command
`npm install aspnet-webpack-react@2.0.1`

Output
```
> aspnet-webpack-react@2.0.1 postinstall D:\Development\PromappApi\PromappApiClient\node_modules\aspnet-webpack-react
> node scripts/postinstall.js

{ Error: Found '{' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 1,1 >>>{
  "compileOnSave" ...
    at error (D:\Development\PromappApi\PromappApiClient\node_modules\hjson\lib\hjson-parse.js:40:11)
    at keyname (D:\Development\PromappApi\PromappApiClient\node_modules\hjson\lib\hjson-parse.js:158:9)
    at object (D:\Development\PromappApi\PromappApiClient\node_modules\hjson\lib\hjson-parse.js:356:15)
    at rootValue (D:\Development\PromappApi\PromappApiClient\node_modules\hjson\lib\hjson-parse.js:426:28)
    at module.exports (D:\Development\PromappApi\PromappApiClient\node_modules\hjson\lib\hjson-parse.js:444:10)
    at Object.parse (D:\Development\PromappApi\PromappApiClient\node_modules\hjson\lib\hjson.js:161:14)
    at ensureTsConfigContainsTypesEntry (D:\Development\PromappApi\PromappApiClient\node_modules\aspnet-webpack-react\scripts\postinstall.js:31:39)
    at Object.<anonymous> (D:\Development\PromappApi\PromappApiClient\node_modules\aspnet-webpack-react\scripts\postinstall.js:51:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10) hint: '' }
promapp-api-client@1.0.0 D:\Development\PromappApi\PromappApiClient
`-- aspnet-webpack-react@2.0.1  invalid
  +-- @types/webpack@2.2.15
  | +-- @types/node@8.0.3
  | +-- @types/tapable@0.2.3
  | `-- @types/uglify-js@2.6.29
  |   `-- @types/source-map@0.5.0
  `-- hjson@2.4.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN promapp-api-client@1.0.0 No repository field.
```

**Comment by wenkangjing** [comment] 2017-06-27 05:32
I followed this walk around and it worked. SteveSandersonMS' reply [issue 1066](https://github.com/aspnet/JavaScriptServices/issues/1066#issuecomment-311039881) 

> To get this workaround in an existing project, just reinstall all your NPM dependencies. For example, delete your project's node_modules directory completely, then run npm install. New projects should get it automatically. You might have to clear your NPM cache first if that still isn't getting the new aspnet-webpack-react version 2.0.1.

- deleted `node_modules` folder
- `npm cache clean --force`
- `dotnet restore` and `dotnet build`
- `npm install`
- `webpack`

**Comment by ruskindantra** [comment] 2017-06-27 05:47
The above mentioned work around doesn't work, it all works the first time after doing that.  As soon you clean your project, i.e. delete `node_modules`, `bin` and `obj` directories and then do a `dotnet build` again it fails.  Note that the `webpack` command is run as part of our `csproj` `BeforeBuild` target.

**Comment by wenkangjing** [comment] 2017-06-27 06:07
I didn't explicitly install `aspnet-webpack-react` to my project, it should automatically link via SpaServices. Restore or delete/readd NuGet packages should works for me.

**Comment by SteveSandersonMS** [comment] 2017-06-27 15:37
@shaunrfield @ruskindantra Do you work together? Just trying to understand whether this is failing in one specific project, or in two completely unrelated projects built by teams that have never met before!

Based on the stack trace, it sounds like your `tsconfig.json` file is invalid. The stack trace is saying it found that file, but can't parse it. Would you be able to verify that the file is correctly-formed JSON (optionally with comments)? If you believe it is correctly formed, can you paste a copy of it here for me to try to reproduce the issue?

**Comment by ruskindantra** [comment] 2017-06-27 22:51
@SteveSandersonMS yes we are working on the same project.  See below our tsconfig.json, it hasn't changed since the new release of `aspnet-webpack-react`.

````
{
  "compileOnSave": true,
  "compilerOptions": {
    "outDir": "./wwwroot/dist/",
    "sourceMap": true,
    "noImplicitAny": false,
    "module": "commonjs",
    "target": "es5",
    "jsx": "react",
    "typeRoots": [ "./node_modules/@types/*", "./node_modules/*" ]
  },
  "include": [
    "./Views/**/Components/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
````

**Comment by SteveSandersonMS** [comment] 2017-06-28 08:34
Thanks for posting the `tsconfig.json` contents. I'm afraid I've not been able to reproduce the issue - your `tsconfig.json` file looks fine, and I don't get any error when I install `aspnet-webpack-react@2.0.1`.

Can you provide more detailed repro steps, starting from a new project?

**Comment by SteveSandersonMS** [comment] 2017-07-03 09:03
Since we don't have any more information about how to reproduce this, and nobody else is reporting anything similar, I'll close this as not being a general bug but rather something specific to your project. If you do find repro steps in the future, please re-open or file a new issue. Hope that's OK!

**Closed by SteveSandersonMS** 2017-07-03 09:03 UTC

**Comment by vvillasanteg** [comment] 2017-07-19 22:58
I had the same issue. This issue was only reproing for me in my VSTS build agent that has a node version 6.10.3.
