### ISSUE TITLE
Provide a React template in ES6 syntax

### ISSUE THREAD

**Issue by xabikos** [aspnet/JavaScriptServices#117] opened 2016-06-07 18:58 UTC
I think it's quite essential to provide a React Redux template in ES6 syntax. In general TypeScript is getting more and more popular among Angular developers. But in the React community ES6 is more popular.

**Comment by SteveSandersonMS** [comment] 2016-06-08 12:17
Closing as duplicate of #118

**Closed by SteveSandersonMS** 2016-06-08 12:17 UTC
