### ISSUE TITLE
Yeoman templates not creating .gitignore file

### ISSUE THREAD

**Issue by MarkPieszak** [aspnet/JavaScriptServices#275] opened 2016-08-25 14:29 UTC
https://github.com/aspnet/JavaScriptServices/blob/dev/templates/package-builder/src/build/build.ts#L31-L41

Not as familiar with the yeoman template builder, but it looks like the code here isn't creating the neccessary `.gitignore` file from `template_gitignore`. The code does look fine though, still looking into it to see if I can find it. Just wanted to get the issue out there.

Also, these files should be excluded as well (after manually creating the .gitignore, these are still not ommited). Should we add these to the `template_gitignore` as well, after fixing the underlying issue?

bin\Debug & obj\Debug files:

![image](https://cloud.githubusercontent.com/assets/2574412/18018450/f71ba78e-6ba4-11e6-8d0c-071fa73a18c9.png)

![image](https://cloud.githubusercontent.com/assets/2574412/18018460/0b3fc5b0-6ba5-11e6-95d1-93651c7ef9d9.png)

**Comment by SteveSandersonMS** [comment] 2016-09-01 13:24
As far as I can tell, both of these things do work already (creating the `.gitignore`, and excluding `bin`/`obj` and all their contents).

If you can still reproduce an issue with either of these, can you supply either repro steps (there has to be something unique about your environment), or ideally track down what the bug is? Or if anyone else can repro either of these issues, please let us know.

**Comment by SteveSandersonMS** [comment] 2016-09-07 14:10
I'll close this due to absence of info, but will keep a lookout in case anything similar occurs in any case I observe.

**Closed by SteveSandersonMS** 2016-09-07 14:10 UTC

**Comment by MarkPieszak** [comment] 2016-09-07 14:25
@SteveSandersonMS Apologies for the delay I tried reproducing on a new project and it seems it has gone away. I believe this was because I was testing creating a project, then uploading it to git (and somehow I must of not pushed the original `.gitignore` to the repo).

Everything is fine, sorry about that :)
