### ISSUE TITLE
Publish give MSB3030 error when wwwroot/dist assets are deleted and recreated as part of MSBuild Exec task

### ISSUE THREAD

**Issue by asadsahi** [aspnet/JavaScriptServices#783] opened 2017-03-22 14:08 UTC
I have custom webpack configuration in my project, which generate javascript bundles in wwwroot/dist folder when running project under dev mode. Here is how it looks:

![image](https://cloud.githubusercontent.com/assets/3470892/24201227/558139e6-0f07-11e7-91ac-359b91a4c560.png)

While these dev assets are still in wwwroot/dist directory and we do `dotnet publish` or publish from visual studio IDE. There is a custom task as configured in angular 2 spa template csproj file.

```
 <Target Name="RunWebpack" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <!--<Exec Command="npm install" />-->
    <Exec Command="npm run build:prod" />

    <!-- Include the newly-built files in the publish output -->
    <ItemGroup>
      <DistFiles Include="wwwroot\dist\**\**;" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
```

`npm run build:prod` is an npm script which cleans wwwroot/dist directory and then creates minified assets, which look like this:
![image](https://cloud.githubusercontent.com/assets/3470892/24201518/2805b1ee-0f08-11e7-9f84-9fc55a3931c1.png)

However, as soon as `npm run build:prod` finishes, I get following error:

![image](https://cloud.githubusercontent.com/assets/3470892/24201503/1f107b46-0f08-11e7-8167-c769b9654453.png)

It looks like the files are read by MSBuild and there is a race conditions between MSBuild and its Exec task in a sense that MSBuild doesn't wait for the Exec task to finish first.

This project is upgraded from project.json based architecture and we never had this issues as there was pre-publish task which finished first and give dotnet publish chance to pickup latest wwwroot/dist files.

Not sure if https://github.com/aspnet/JavaScriptServices/issues/735 is linked to this as well.

**Comment by SteveSandersonMS** [comment] 2017-03-22 15:38
I suspect that, rather than being a race condition, it might be something more like the WebSDK publish task being set up in such a way that it collects references to the files to be published first, then runs your `<Exec>` task, and then tries to copy some files that no longer exist. But I don't know for sure - you'd have to read through how the WebSDK MSBuild code works internally. It's possible that your current custom setup just doesn't work with the dynamic `ResolvedFileToPublish` replacement in some way.

It's likely that this issue could be reproduced on a simple ASP.NET project without using JavaScriptServices templates, since the only part relevant to your report is the small snippet of MSBuild config you posted. If you think there's a bug in the WebSDK, could you please report it to its issue list at https://github.com/aspnet/websdk/issues?

I'll close this issue here because it's certainly not something controlled in the JavaScriptServices repo code. Hope that's OK!

**Closed by SteveSandersonMS** 2017-03-22 15:38 UTC

**Comment by asadsahi** [comment] 2017-03-24 12:52
@SteveSandersonMS Thanks.

This has fixed it:

https://github.com/aspnet/websdk/issues/162#issuecomment-288850434

Here is my updated csproj.
https://github.com/asadsahi/AspNetCoreSpa/blob/master/AspNetCoreSpa.csproj
