### ISSUE TITLE
Ctrl+S does not trigger HMR in Angular 2 template project

### ISSUE THREAD

**Issue by dubesinhower** [aspnet/JavaScriptServices#536] opened 2016-12-22 21:51 UTC
I created a brand new Angular 2 project using the template. Right away, I tried to test the hot module replacement feature by starting the IIS server, editing one of the component html templates, and saving the file by pressing Ctrl+S, but the change never made it to the browser.

I made the same change, pressed the floppy disk "Save Selected Items" button, and HRM updated the browser.

Is there a problem with the template configuration? Is there some conflicting plugin that I'm using that might be hijacking the Ctrl+S hotkey (Resharper) or something?

**Comment by MarkPieszak** [comment] 2016-12-22 22:40
Is it happening in visual studio? 
Go to Options - Environment - Keyboard to check out what Ctrl-S is doing currently. You're right there might be something that's stopping it from actually saving the file.

**Comment by dubesinhower** [comment] 2016-12-23 13:18
It says the command "File.SaveSelectedItems" is set to Ctrl+S (Global).

**Comment by MarkPieszak** [comment] 2016-12-23 13:52
Can you try disabling a few big add ons and see if that helps at all?

**Comment by dubesinhower** [comment] 2016-12-23 15:38
I disabled Resharper, and it doesn't seem to help. I've even come across an issue where if I use Ctrl+S to save a file, then any updates made after saved with the save button don't trigger HMR.

**Comment by SteveSandersonMS** [comment] 2017-01-02 10:25
This is really weird, but since it's specifically a difference between Ctrl+S and clicking the "save" icon, it's got to be something inside Visual Studio or some other add-in you have installed. The code in this repo is *not* a VS add-in, so it can't possibly interact with VS at the level of differentiating between Ctrl+S and clicking "save". The code here doesn't even have any concept of either: it just sees files changing on disk.

I'll have to close this because there's nothing we could do inside this repo that would fix this for you. Sorry! If you just want the problem to go away, you could try reinstalling VS (or even Windows as a whole, in case it turns out to be some totally unrelated software that interferes with Ctrl+S keystrokes).

If somehow you figure out how anyone could reproduce this issue (e.g., on a new Windows + Visual Studio installation, what steps to take to get VS into a state where this happens), please do let us know.

**Closed by SteveSandersonMS** 2017-01-02 10:25 UTC
