### ISSUE TITLE
update `aspnet-webpack` to webpack 3

### ISSUE THREAD

**Issue by pfrendo** [aspnet/JavaScriptServices#1149] opened 2017-07-26 11:18 UTC

**Comment by stephtr** [comment] 2017-07-26 13:12
A newer version of `aspnet-webpack` isn't required for running webpack 3, I think at the moment it is relatively safe to ignore the warning about that when restoring packages.

**Comment by gaspardle** [comment] 2017-07-26 20:33
Yes but then we can't do `npm shrinkwrap`

**Comment by SteveSandersonMS** [comment] 2017-07-27 11:40
Duplicate of #1126

**Closed by SteveSandersonMS** 2017-07-27 11:40 UTC
