### ISSUE TITLE
Problem in "dotnet new -i "Microsoft.AspNetCore.SpaTemplates::*"

### ISSUE THREAD

**Issue by Shawn-Fan** [aspnet/JavaScriptServices#1181] opened 2017-08-10 22:03 UTC
I run dotnet new -i "Microsoft.AspNetCore.SpaTemplates::*" , but i got 2 angular templates tags with same short name same follow:

Templates Tags Short Name Language
......
MVC ASP.NET Core With Angular Web/MVC/SPA angular [C#]
ASP.NET Core with Angular Web/MVC/SPA angular [C#]
.......
![image](https://user-images.githubusercontent.com/15960295/29194107-6c62a896-7de5-11e7-84e5-da30ac6029ab.png)

so , I can not use "dotnet new angular". Please help me how to delete another Template Tag or select one?

**Comment by SteveSandersonMS** [comment] 2017-08-14 09:09
Closing as duplicate of https://github.com/dotnet/templating/issues/1201

**Closed by SteveSandersonMS** 2017-08-14 09:09 UTC
