### ISSUE TITLE
EACCESS error on aspnetcore-spa generator install

### ISSUE THREAD

**Issue by unnsteinngardars** [aspnet/JavaScriptServices#1032] opened 2017-06-12 23:45 UTC
When trying to install the aspnetcore-spa generator I get a bunch of warnings and errors, the errors are pointing to me having a permission issue and some of the warnings are informing me that some directories were not found.

➜  ~ npm i generator-aspnetcore-spa
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN enoent ENOENT: no such file or directory, open '/Users/unnsteinngardarsson/package.json'
npm WARN unnsteinngardarsson No description
npm WARN unnsteinngardarsson No repository field.
npm WARN unnsteinngardarsson No README data
npm WARN unnsteinngardarsson No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lodash@4.17.4 (node_modules/ast-query/node_modules/lodash):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/Users/unnsteinngardarsson/node_modules/.staging/lodash-5c2e9596/_hashClear.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lodash@4.17.4 (node_modules/yeoman-environment/node_modules/lodash):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/Users/unnsteinngardarsson/node_modules/.staging/lodash-0364bfd0/intersectionWith.js'

npm ERR! path /Users/unnsteinngardarsson/node_modules/.staging/generator-aspnetcore-spa-a1d41fa9/.npmignore
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
npm ERR! Error: EACCES: permission denied, open '/Users/unnsteinngardarsson/node_modules/.staging/generator-aspnetcore-spa-a1d41fa9/.npmignore'
npm ERR!  { Error: EACCES: permission denied, open '/Users/unnsteinngardarsson/node_modules/.staging/generator-aspnetcore-spa-a1d41fa9/.npmignore'
npm ERR!   cause:
npm ERR!    { Error: EACCES: permission denied, open '/Users/unnsteinngardarsson/node_modules/.staging/generator-aspnetcore-spa-a1d41fa9/.npmignore'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'open',
npm ERR!      path: '/Users/unnsteinngardarsson/node_modules/.staging/generator-aspnetcore-spa-a1d41fa9/.npmignore' },
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/Users/unnsteinngardarsson/node_modules/.staging/generator-aspnetcore-spa-a1d41fa9/.npmignore' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/unnsteinngardarsson/.npm/_logs/2017-06-12T23_41_08_880Z-debug.log

I have tried using the -g flag to install globally, I have also changed the owner of the /usr/local folder and all its subfolders to my account and also changed the permissions for all folders and files inside /usr/local aswell. I also made a folder on my desktop trying to install it there but nothing seems to work, I always get the same warnings and errors.

I have tried to install other generators such as the aspnet generator and aspnet-spa and that seems to be working fine. 

I am really banging my head against the wall at this moment and am really hoping that someone can help me resolve this issue.
![screen shot 2017-06-12 at 11 44 26 pm](https://user-images.githubusercontent.com/24224030/27060021-a648d46c-4fc9-11e7-8d38-3a7b666ed266.png)

**Comment by SteveSandersonMS** [comment] 2017-06-13 08:41
This looks like a problem with your Node/NPM installation. I'd recommend removing all traces of it from your machine and starting again.

Sorry it's not something that could be fixed in this repo, as the problem is occurring before you even have the generator installed.

**Closed by SteveSandersonMS** 2017-06-13 08:41 UTC

**Comment by ckrassas** [comment] 2017-06-26 10:27
Not sure if this issue was resolved for @unnsteinngardars. As @SteveSandersonMS pointed out this is an issue with Node/NPM. 

I had no issues on one of my computers with Node v6.x/NPM v3.x and the other PC with Node v8.x/NPM v5.x had exact same errors. I reverted the version to the LTS release and everything was installed and worked properly!
