### ISSUE TITLE
Typescript 2, Webpack 2, Angular 2 upgrade?

### ISSUE THREAD

**Issue by asadsahi** [aspnet/JavaScriptServices#318] opened 2016-09-17 21:54 UTC
I just wanted to understand if this upgrade will have any issues because of any aspnetcore-spa package require changes?

I have just managed to upgrade one of [my project](https://github.com/asadsahi/AspNetCoreSpa) (based on angular 2 template of aspnetcore-spa generator) to typescript 2, webpack 2 and Angular 2 successfully. This project is still using  "aspnet-webpack": "1.0.11".

Is there an official upgrade plan?

**Comment by MarkPieszak** [comment] 2016-09-17 21:59
I just posted the PR (https://github.com/aspnet/JavaScriptServices/pull/319) to upgrade to Angular 2.0.0, Universal 2.0.7, Preboot 4.*, and TypeScript 2.0 (which I needed to be able to include universal 2.*.

This includes the NgModules, separate ones for both Client & Server, and is connected with the latest Universal updates.

:)

**Comment by asadsahi** [comment] 2016-09-17 22:05
Good to hear that @MarkPieszak . What about webpack 2? Are we waiting for it to be final?

**Comment by MarkPieszak** [comment] 2016-09-17 22:09
I thought about it! But I believe we might need some changes to the `asp-webpack` package potentially, didn't want to get into all of that today 😛 

Maybe next week? I believe they'll be out of beta real soon too.

**Comment by asadsahi** [comment] 2016-09-17 22:14
I upgraded the same project to webpack 2 and dev and prod  files are generated without error. Had to upgrade some peer packages of webpack though. Probably need to get some work for Angular 2 AOT to include in production as optional step.

**Comment by hheexx** [comment] 2016-09-18 15:13
I merged pull request with my project and nothing is broken.
Works perfectly for me in dev environment.
It's not yet in production, it will be in a month. I hope things will further stabilize until then.

Thanks a ton Mark for fast response!

**Comment by MarkPieszak** [comment] 2016-09-18 16:01
What do you mean by the production story? @asadsahi 
We do (newly) support AoT compilation with Universal, but I haven't tried connecting it with .NET Core just yet, I can try and do that next with upgrading to webpack2. 

Not a problem @hheexx 😀

**Comment by asadsahi** [comment] 2016-09-18 16:28
Hi @MarkPieszak from production story I meant does your pull request cater for webpack production buids which compiles Angular 2 with AOT Cli and then rollup to reduce the bundle size. Currently production builds produce bundle sizes in MBs just by uglifying javascript.

With AOT + Rollup + Gzip (hopefully by the server) bundle size should dramatically be reduced.

**Comment by SteveSandersonMS** [comment] 2016-09-19 07:52
Lots of good info here - thanks for the info @MarkPieszak  and @asadsahi. Closing as it's not a bug/issue, but the discussion can continue if desired.

**Closed by SteveSandersonMS** 2016-09-19 07:52 UTC

**Comment by tinchou** [comment] 2016-09-30 18:18
Would love to see Webpack 2 working with aspnet-webpack, especially because of the tree shaking feature.

@asadsahi did you run into any issues when upgrading? Did you notice the expected size shrink with Webpack 2?
