### ISSUE TITLE
gitlab-ci configuration 

### ISSUE THREAD

**Issue by JonathanLoscalzo** [aspnet/JavaScriptServices#1050] opened 2017-06-21 12:41 UTC
This is my gilab-ci.yml config: 

> image: microsoft/dotnet:2.0-sdk
> services: 
>   - node:8.1
> stages:
>   - build
> before_script:
>   - 'cd webapp'
>   - 'npm install'
>   - 'cd ../'
>   - 'dotnet restore'
> build:
>  stage: build
>  script:
>   - 'dotnet build'
>  only:
>    - development

The problem is that dotnet:2.0-sdk image doesn't have node, but installing node as a service (like postgres service), not run...

anybody have to run a javascript services project on GitLab?
thanks!

**Comment by SteveSandersonMS** [comment] 2017-06-21 13:26
By all means please continue this discussion here. I'm just marking it as closed because it's not a bug or feature request that would lead us to make any changes in this repo. Hope that's OK!

**Closed by SteveSandersonMS** 2017-06-21 13:26 UTC
