### ISSUE TITLE
Why is site.css loaded only for staging and production?

### ISSUE THREAD

**Issue by TravisBoatman** [aspnet/JavaScriptServices#610] opened 2017-01-26 20:02 UTC
I created my own webpack config and bundled everything into a single `site.css`. In `_Layout.cshtml` I removed `vendor.css` and had `site.css` load by default. I saw no changes, HMR still worked. What's the purpose for this?

**Comment by SteveSandersonMS** [comment] 2017-01-27 09:39
You haven't mentioned which project template you're comparing with, but I'm guessing the React (non-Redux) or Knockout one because they work in the way you've described. Please let me know if you mean a different one.

When you say *HMR still worked*, do you mean just for TypeScript changes, or for CSS changes too? How are you bundling all the CSS into `site.css`? Are you using `ExtractTextPlugin` and `css-loader`? At least last time I checked, HMR (for CSS changes) wasn't supported with `ExtractTextPlugin`+`css-loader`. That's why we use `style-loader` in development (it does support HMR for CSS changes).

I'll close this since it appears to be working as designed, but please let me know if you actually do have HMR for CSS changes working with `ExtractTextPlugin` (which, at least last time I checked, the Webpack folks said should not be used in development mode).

**Closed by SteveSandersonMS** 2017-01-27 09:39 UTC

**Comment by TravisBoatman** [comment] 2017-01-27 21:29
Yes, this is with the Knockout template. I never tried changing the css file. Just tried it and it does not work with HMR, requires a browser refresh. Here's my own webpack config

```
var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

var config = {
    resolve: { extensions: [ '', '.js', '.ts' ] },
    entry: {
        app: [
            './boot.ts'
        ]
    },
    output: {
        path: path.join(__dirname, '../WebApp/wwwroot/dist/'),
        filename: 'main.js',
        publicPath: '/dist/'
    },
    plugins: [
        new ExtractTextPlugin("site.css"),
        new webpack.ProvidePlugin({
            '$': "jquery",
            'jQuery': "jquery",
            'window.jQuery': "jquery",
            'window.$': 'jquery'
        }),
        new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.js', Infinity),
    ],
    module: {
        noParse: [],
        loaders: [
            {
                test: /\.ts$/,
                loader: 'ts-loader',
                query: { silent: true }
            },
            {
                test: /\.html$/,
                loader: 'raw-loader' 
            },
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract('style-loader', 'css-loader')
            },
            {
                test: /\.(png|jpg|gif)(\?v=\d+\.\d+\.\d+)?$/,
                loader: 'url-loader?limit=100000'
            },
            {
                test: /\.(eot|com|json|ttf|woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
                loader: 'url-loader?limit=10000&mimetype=application/octet-stream'
            },
            {
                test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
                loader: 'url-loader?limit=10000&mimetype=image/svg+xml'
            }
        ]
    }
};


module.exports = config;
```

So if I understand correctly `site.css` is only loaded for staging and production because you support CSS HMR in development?

**Comment by SteveSandersonMS** [comment] 2017-01-30 10:42
> So if I understand correctly site.css is only loaded for staging and production because you support CSS HMR in development?

Correct :)
